### ISSUE TITLE
install electron-builder error in win 10

### ISSUE THREAD

**Issue by GeeshangXu** [cnpm/cnpm#103]
I am using windows 10, when i  use command "**cnpm** install  electron-builder --save-dev", i got following error. electron-builder V3.5.0

>..\src\volume.cc(9): fatal error C1189: #error: This platform is not implemented yet [D:\electron->quick->start\node_modules.npminstall\macos-alias\0.2.9\macos-alias\b
>uild\volume.vcxproj]

But command "**npm** install electron-builder  --save-dev" is ok.

**Comment by dead-horse** [comment]
macos?

**Comment by GeeshangXu** [comment]
No, i am using windows 10.

**Comment by fengmk2** [comment]
`This platform is not implemented yet`

**Comment by GeeshangXu** [comment]
@fengmk2 这应该是cnpm的问题，因为用原生的npm安装就没有任何错误。

**Comment by zxc122333** [comment]
安装chokidar时同样的问题，应该是对package.json的OS字段检查出了问题
chokida optionalDependencies fsevents
fsevents os:["darwin"]

这个貌似应该是由npm处理的啊。。

环境：
Windows 10
node v5.10.1
npm 3.8.3
cnpm 4.2.0

相关日志：
```
G:\fish\fishClient                                                                                                                  
λ npm i chokidar                                                                                                                    
fishclient@ G:\fish\fishClient                                                                                                      
`-- chokidar@1.4.3  extraneous                                                                                                      
                                                                                                                                    
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:                                                           
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11                                          
npm WARN fishclient@ No repository field.                                                                                           
npm WARN fishclient@ No license field.        

                                                                                      
G:\fish\fishClient                                                                                                                  
λ rm .\node_modules\                                                                                                                
                                                                                                                                    
确认                                                                                                                                  
G:\fish\fishClient\node_modules\ 处的项具有子项，并且未指定 Recurse 参数。如果继续，所有子项均将随该项删除。是否确实要继续?                                                 
[Y] 是(Y)  [A] 全是(A)  [N] 否(N)  [L] 全否(L)  [S] 暂停(S)  [?] 帮助 (默认值为“Y”):  y            

                                                
G:\fish\fishClient                                                                                                                  
λ cnpm i chokidar                                                                                                                   
[fsevents@1.0.11] download from binary mirror: {"module_name":"fse","module_path":"./lib/binding/{configuration}/{node_abi}-{platfor
m}-{arch}/","remote_path":"./v{version}/","package_name":"{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz","host":"http
s://npm.taobao.org/mirrors/fsevents"}                                                                                               
[chokidar@*] installed at node_modules\.npminstall\chokidar\1.4.3\chokidar (0 packages, use 7s, speed 53.84kB/s, json 382.33kB, tarb
all 0B)                                                                                                                             
excute post install scripts...                                                                                                      
[fsevents@1.0.11] scripts.install: "node-pre-gyp install --fallback-to-build" at G:\fish\fishClient\node_modules\.npminstall\fsevent
s\1.0.11\fsevents                                                                                                                   
node-pre-gyp http GET https://npm.taobao.org/mirrors/fsevents/v1.0.11/fse-v1.0.11-node-v47-win32-x64.tar.gz                         
node-pre-gyp http 404 https://npm.taobao.org/mirrors/fsevents/v1.0.11/fse-v1.0.11-node-v47-win32-x64.tar.gz                         
node-pre-gyp http Pre-built binary not available for your system, looked for https://npm.taobao.org/mirrors/fsevents/v1.0.11/fse-v1.
0.11-node-v47-win32-x64.tar.gz (falling back to source compile with node-gyp)                                                       
node-pre-gyp ERR! build error                                                                                                       
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd clean' (Error: spawn node-gyp.cmd ENOENT)                            
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (G:\fish\fishClient\node_modules\.npminstall\fsevents\1.0.11\fsevents\node_m
odules\node-pre-gyp\lib\util\compile.js:77:29)                                                                                      
node-pre-gyp ERR! stack     at emitOne (events.js:90:13)                                                                            
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:7)                                                                  
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)                               
node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:348:16)                                                         
node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)                                          
node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:98:9)                                           
node-pre-gyp ERR! System Windows_NT 10.0.10586                                                                                      
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "G:\\fish\\fishClient\\node_modules\\.npminstall\\fsevents\\1.0.11\\
fsevents\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"                                            
node-pre-gyp ERR! cwd G:\fish\fishClient\node_modules\.npminstall\fsevents\1.0.11\fsevents                                          
node-pre-gyp ERR! node -v v5.10.1                                                                                                   
node-pre-gyp ERR! node-pre-gyp -v v0.6.25                                                                                           
node-pre-gyp ERR! not ok                                                                                                            
Failed to execute 'node-gyp.cmd clean' (Error: spawn node-gyp.cmd ENOENT)                                                           
[Error: Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build" error, exit code 1                      
    at ChildProcess.<anonymous> (C:\Users\sqh\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:67:21)          
    at emitTwo (events.js:100:13)                                                                                                   
    at ChildProcess.emit (events.js:185:7)                                                                                          
    at maybeClose (internal/child_process.js:850:16)                                                                                
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)@%s] optional error: %s                                 
All packages installed (71 packages installed from npm registry, use 10s, speed 38.83kB/s, json 73(382.33kB), tarball 0B)           

```

**Comment by mirror-riddle** [comment]
Got the same error on Ubuntu 16.04 :sob:

**Comment by fengmk2** [comment]
@GeeshangXu @mirror-riddle @zxc122333 请重新安装 cnpm，应该已经修复了。在 ubuntu 测试通过

![image](https://cloud.githubusercontent.com/assets/156269/15093501/a660159e-14bc-11e6-81a0-4cb9c53e1880.png)

**Comment by fengmk2** [comment]
在 Windows 上也是 ok 了 https://ci.appveyor.com/project/fengmk2/npminstall/build/1.0.452/job/s6tdebw3fkjserp5#L1118

![image](https://cloud.githubusercontent.com/assets/156269/15093513/10311fae-14bd-11e6-815c-292eddf2554a.png)

**Comment by mirror-riddle** [comment]
@fengmk2 可以用了，美中不足的地方是安装electron-builder时会提示错误：

> [appdmg@0.3.7](./node_modules/.npminstall/electron-builder/2.1.1/electron-builder/node_modules/appdmg) unsupported: Package require os(darwin) not compatible with your platform(linux)
[appdmg@^0.3.1] optional install error:
Error: Package require os(darwin) not compatible with your platform(linux)
    at _install (/usr/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:150:19)
    at next (native)
    at onFulfilled (/usr/lib/node_modules/cnpm/node_modules/npminstall/node_modules/co/index.js:65:19)
>

看起来好像真出了什么错误一样。实际上这也不算错误，应该是警告。

对比一下，用npm 安装electron-builder时，只会提示警告 

> npm WARN optional dep failed, continuing appdmg@0.3.7

希望可以改进。:smile:

**Comment by alsotang** [comment]
错误提示中的  os(darwin) 是 mac 系统

2016-05-08 11:30 GMT+08:00 Jin He <notifications@github.com>:

**Comment by alsotang** [comment]
粗看像是 npminstall 的 bug

2016-05-08 16:54 GMT+08:00 alsotang <alsotang@gmail.com>:

**Comment by fengmk2** [comment]
@mirror-riddle 提示的是 optional，不影响的 `[appdmg@^0.3.1] optional install error:`

![image](https://cloud.githubusercontent.com/assets/156269/15097744/5bc21d1a-1558-11e6-8337-5acdd8a5afda.png)

最终提示 `[electron-builder@*] installed ` 就代表成功了。

```bash
[electron-builder@*] installed at node_modules/.npminstall/electron-builder/3.17.1/electron-builder (0 packages, use 8s, speed 384.59kB/s, json 2.3MB, tarball 544.11kB)
```

**Comment by fengmk2** [comment]
看来得将 optional error 弱化一下

![image](https://cloud.githubusercontent.com/assets/156269/15097766/86136712-1559-11e6-887f-2ae9e3bd1dd7.png)

**Comment by fengmk2** [comment]
改变后 
![image](https://cloud.githubusercontent.com/assets/156269/15098285/135c5428-156c-11e6-85f5-13e65a99123e.png)
