### ISSUE TITLE
sh: node-gyp: command not found

### ISSUE THREAD

**Issue by meteormatt** [cnpm/cnpm#105]
用cnpm安装源码的模块现在都有问题. 用npm是正常的.

```bash
$ cnpm install node-icu-charset-detector
[node-icu-charset-detector@*] installed at node_modules/.npminstall/node-icu-charset-detector/0.1.4/node-icu-charset-detector (0 packages, use 307ms, speed 20.17kB/s, json 6.25kB, tarball 0B)
excute post install scripts...
[node-icu-charset-detector@0.1.4] scripts.install: "node-gyp rebuild" at /Users/Meteor/workspace_test/irc-meeting-bot/node_modules/.npminstall/node-icu-charset-detector/0.1.4/node-icu-charset-detector
sh: node-gyp: command not found
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 127
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 127
    at ChildProcess.proc.on.code (/Users/Meteor/.nvm/versions/node/v6.0.0/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

```bash
node -v
v6.0.0
cnpm -v
4.2.0
npm -v
3.8.7
```

**Comment by alsotang** [comment]
node 6.0 这几天问题会很多的。。你换个5.x或者4.x试试？

2016-04-27 16:13 GMT+08:00 Liu Xing <notifications@github.com>:

**Comment by meteormatt** [comment]
5.11上也不行
```bash
$ cnpm install node-icu-charset-detector
[node-icu-charset-detector@*] installed at node_modules/.npminstall/node-icu-charset-detector/0.1.4/node-icu-charset-detector (0 packages, use 297ms, speed 20.91kB/s, json 6.25kB, tarball 0B)
excute post install scripts...
[node-icu-charset-detector@0.1.4] scripts.install: "node-gyp rebuild" at /Users/Meteor/workspace_test/irc-meeting-bot/node_modules/.npminstall/node-icu-charset-detector/0.1.4/node-icu-charset-detector
sh: node-gyp: command not found
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 127
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 127
    at ChildProcess.<anonymous> (/Users/Meteor/.nvm/versions/node/v5.11.0/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
$ node -v
v5.11.0
```

**Comment by dead-horse** [comment]
先装一个 node-gyp

`tnpm install node-gyp -g`

**Comment by meteormatt** [comment]
现在可以了.
不过为什么npm可以,但是cnpm一定要装个`node-gyp`呢?

**Comment by dead-horse** [comment]
npm 自带了 node-gyp，我们后续会在 cnpm 这里加上

**Comment by meteormatt** [comment]
好吧. 看到4.2.0版本的[更新说明](../blob/master/History.md)了. 
  * refactor: remove node-gyp
8361cbc47cded981765ca40b9be0c64abc1b6ae6

**Comment by fengmk2** [comment]
close by https://github.com/cnpm/npminstall/pull/75

**Comment by meteormatt** [comment]
:+1:

**Comment by yinmazhong** [comment]
13
