### ISSUE TITLE
cnpm i yeoman -g 报错

### ISSUE THREAD

**Issue by magicdawn** [cnpm/cnpm#113]
## `cnpm i yeoman -g` 报错

1 错误
```
[connect@2.2.2] install error: Error: GET http://registry.npm.taobao.org/crc/download/crc-0.1.0.tgz response 404 status, parentDir: /Users/magicdawn/.nvm/versions/node/v4.4.4/lib/node_modules/.yeoman_npminstall/yeoman/0.9.6/yeoman, remove /Users/magicdawn/.nvm/versions/node/v4.4.4/lib/node_modules/.yeoman_npminstall/connect/2.2.2/connect
error stack: Error: GET http://registry.npm.taobao.org/crc/download/crc-0.1.0.tgz response 404 status
    at get (/Users/magicdawn/.nvm/versions/node/v4.4.4/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:55:11)
    at next (native)
    at onFulfilled (/Users/magicdawn/.nvm/versions/node/v4.4.4/lib/node_modules/cnpm/node_modules/npminstall/node_modules/co/index.js:65:19)
[yeoman@0.9.6] install error: Error: GET http://registry.npm.taobao.org/crc/download/crc-0.1.0.tgz response 404 status, parentDir: /Users/magicdawn/.nvm/versions/node/v4.4.4/lib, remove /Users/magicdawn/.nvm/versions/node/v4.4.4/lib/node_modules/.yeoman_npminstall/yeoman/0.9.6/yeoman
error stack: Error: GET http://registry.npm.taobao.org/crc/download/crc-0.1.0.tgz response 404 status
    at get (/Users/magicdawn/.nvm/versions/node/v4.4.4/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:55:11)
    at next (native)
    at onFulfilled (/Users/magicdawn/.nvm/versions/node/v4.4.4/lib/node_modules/cnpm/node_modules/npminstall/node_modules/co/index.js:65:19)
Error: GET http://registry.npm.taobao.org/crc/download/crc-0.1.0.tgz response 404 status
Error: GET http://registry.npm.taobao.org/crc/download/crc-0.1.0.tgz response 404 status
    at get (/Users/magicdawn/.nvm/versions/node/v4.4.4/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:55:11)
    at next (native)
    at onFulfilled (/Users/magicdawn/.nvm/versions/node/v4.4.4/lib/node_modules/cnpm/node_modules/npminstall/node_modules/co/index.js:65:19)
```

![image](https://cloud.githubusercontent.com/assets/4067115/15424658/7e1ad3fe-1eb6-11e6-8ff4-26efaec90f52.png)

2
```
# https://r.cnpmjs.org/crc/sync/log/137086
cnpm sync crc # 成功

# https://r.cnpmjs.org/yeoman/sync/log/137087
cnpm sync yeoman 成功
```

3 再次安装
```
cnpm i yeoman -g # 仍然报错
```

4
```
cnpm -v # 4.2.0
```

**Comment by magicdawn** [comment]
sorry 刚发现是 `yo`

```
cnpm i yo -g
```
