### ISSUE TITLE
cnpm install -g  npm-check-updates 报错

### ISSUE THREAD

**Issue by meteormatt** [cnpm/cnpm#114]
```bash
~$ cnpm install -g  npm-check-updates
[npm-check-updates@2.6.5] install error: Error: npm@3.9.3 sha1:f7c36040feb4175a963c61dadb948dfded978f45 not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3), parentDir: /Users/Meteor/.nvm/versions/node/v6.2.0/lib, remove /Users/Meteor/.nvm/versions/node/v6.2.0/lib/node_modules/.npm-check-updates_npminstall/npm-check-updates/2.6.5/npm-check-updates
error stack: Error: npm@3.9.3 sha1:f7c36040feb4175a963c61dadb948dfded978f45 not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3)
    at ReadStream.readstream.on (/Users/Meteor/.nvm/versions/node/v6.2.0/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:220:24)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Error: npm@3.9.3 sha1:f7c36040feb4175a963c61dadb948dfded978f45 not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3)
Error: npm@3.9.3 sha1:f7c36040feb4175a963c61dadb948dfded978f45 not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3)
    at ReadStream.readstream.on (/Users/Meteor/.nvm/versions/node/v6.2.0/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:220:24)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
换成`npm install -g  npm-check-updates`成功

**Comment by fengmk2** [comment]
npm@3.9.3 的正确 sha1 确实是 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449，按照错误提示来看代表你下载的 npm@3.9.3 包是不正确的，估计是你的网络问题，重跑命令应该能够安装成功的。

```json
dist: 
   { shasum: '1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449',
     size: 52099262,
     noattachment: false,
     tarball: 'http://registry.npm.taobao.org/npm/download/npm-3.9.3.tgz' },
```

**Comment by fengmk2** [comment]
我改进一下

**Comment by meteormatt** [comment]
我这里重新试了好几次还是这个错

**Comment by fengmk2** [comment]
@meteormatt 你重新安装 cnpm，然后重新运行看看效果

**Comment by meteormatt** [comment]
```bash
~/Desktop$ cnpm install npm-check-updates
[npm@3.9.3] download error: npm@3.9.3 sha1:9d63058d3f08aa3d78a8aa6a75499b74e79531a2 not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3), fail count: 1
[npm@3.9.3] download error: npm@3.9.3 sha1:dbc246b425fb4b3b993cdaf2fd86ea95169ce06e not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3), fail count: 2
[npm@3.9.3] download error: npm@3.9.3 sha1:f0a93708194354a5485481ef0b5e8c3ade3d0bd9 not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3), fail count: 3
[npm-check-updates@2.6.5] install error: ShasumNotMatchError: npm@3.9.3 sha1:f0a93708194354a5485481ef0b5e8c3ade3d0bd9 not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3), parentDir: /Users/Meteor/Desktop, remove /Users/Meteor/Desktop/node_modules/.npminstall/npm-check-updates/2.6.5/npm-check-updates
error stack: ShasumNotMatchError: npm@3.9.3 sha1:f0a93708194354a5485481ef0b5e8c3ade3d0bd9 not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3)
    at ReadStream.readstream.on (/Users/Meteor/.nvm/versions/node/v6.2.0/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:248:21)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
ShasumNotMatchError: npm@3.9.3 sha1:f0a93708194354a5485481ef0b5e8c3ade3d0bd9 not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3)
ShasumNotMatchError: npm@3.9.3 sha1:f0a93708194354a5485481ef0b5e8c3ade3d0bd9 not equal to 1b3dd326a2a228ef9a623f1df3a60ff6f4b3c449 (npm@3.9.3)
    at ReadStream.readstream.on (/Users/Meteor/.nvm/versions/node/v6.2.0/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:248:21)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
重装了还是报错

**Comment by meteormatt** [comment]
要不我试试`nvm`重装下`v6.2.0`版本

**Comment by meteormatt** [comment]
我搞不懂为什么我的`npm`版本明明不是`3.9.3`版本. 可是运行`cnpm`出来一直是`3.9.3`

**Comment by fengmk2** [comment]
npm-check-uodates 依赖了这个npm版本吧，奇怪，你下载一直失败。加个 --no-cache 参数呢？

**Comment by meteormatt** [comment]
加了 --no-cache 参数成功了.
```
~/Desktop$ cnpm  install npm-check-updates --no-cache
[npm-check-updates@*] installed at node_modules/.npminstall/npm-check-updates/2.6.5/npm-check-updates (0 packages, use 2m, speed 385.15kB/s, json 437.26kB, tarball 49.89MB)
All packages installed (82 packages installed from npm registry, use 2m, speed 385.1kB/s, json 91(437.26kB), tarball 49.89MB)
```

**Comment by meteormatt** [comment]
现在不出错了. 奇怪. :sweat_smile:
