### ISSUE TITLE
npm安装不会有问题，cnpm安装会有问题

### ISSUE THREAD

**Issue by zhangda89** [cnpm/cnpm#118]
excute post install scripts...
[dtrace-provider@0.6.0] scripts.install: "node scripts/install.js" at ./node_modules/.npminstall/dtrace-provider/0.6.0/dtrace-provider
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at Object.<anonymous> (/Users/durban126/nodejs/qeeniao-api-admin/node_modules/.npminstall/dtrace-provider/0.6.0/dtrace-provider/scripts/install.js:19:20)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
[Error: Run "sh -c node scripts/install.js" error, exit code 1
    at ChildProcess.<anonymous> (/Users/durban126/.nvm/versions/node/v5.3.0/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)@%s] optional error: %s

**Comment by dead-horse** [comment]
`/Users/durban126/nodejs/qeeniao-api-admin/node_modules/.npminstall/dtrace-provider/0.6.0/dtrace-provider/scripts/install.js`

看提示看看这个文件里面调用 path 的时候传递了什么参数？

**Comment by fengmk2** [comment]
```
cnpm i dtrace-provider
[dtrace-provider@*] installed at node_modules/.0.6.0@dtrace-provider (2 packages, use 451ms, speed 130.71kB/s, json 34.03kB, tarball 25.18kB)
execute post install scripts...
[dtrace-provider@0.6.0] scripts.install: "node scripts/install.js" at ./node_modules/.0.6.0@dtrace-provider
[dtrace-provider@0.6.0] scripts.install success, use 6s
All packages installed (2 packages installed from npm registry, use 7s, speed 8.53kB/s, json 2(34.03kB), tarball 25.18kB)
```
