### ISSUE TITLE
install error: JSONResponseFormatError

### ISSUE THREAD

**Issue by taoqf** [cnpm/cnpm#122]
@fengmk2 
i got error when i run
`cnpm i typings`
error message is just like this:
｀｀｀
[form-data@0.2.0] install error: JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)
headers: {"content-type":"text/plain; charset=utf-8","content-length":"21","date":"Fri, 17 Jun 2016 03:08:37 GMT","connection":"keep-alive"}, parentDir: /home/taoqf/work/tmp/node_modules/.npminstall/popsicle/6.2.0/popsicle, remove /home/taoqf/work/tmp/node_modules/.npminstall/form-data/0.2.0/form-data
error stack: JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)
headers: {"content-type":"text/plain; charset=utf-8","content-length":"21","date":"Fri, 17 Jun 2016 03:08:37 GMT","connection":"keep-alive"}
    at Object.parse (native)
    at parseJSON (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:745:24)
    at /home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:618:23
    at decodeContent (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:480:14)
    at IncomingMessage.<anonymous> (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:599:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[popsicle@6.2.0] install error: JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)
headers: {"content-type":"text/plain; charset=utf-8","content-length":"21","date":"Fri, 17 Jun 2016 03:08:37 GMT","connection":"keep-alive"}, parentDir: /home/taoqf/work/tmp/node_modules/.npminstall/typings-core/1.2.2/typings-core, remove /home/taoqf/work/tmp/node_modules/.npminstall/popsicle/6.2.0/popsicle
error stack: JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)
headers: {"content-type":"text/plain; charset=utf-8","content-length":"21","date":"Fri, 17 Jun 2016 03:08:37 GMT","connection":"keep-alive"}
    at Object.parse (native)
    at parseJSON (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:745:24)
    at /home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:618:23
    at decodeContent (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:480:14)
    at IncomingMessage.<anonymous> (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:599:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[typings-core@1.2.2] install error: JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)
headers: {"content-type":"text/plain; charset=utf-8","content-length":"21","date":"Fri, 17 Jun 2016 03:08:37 GMT","connection":"keep-alive"}, parentDir: /home/taoqf/work/tmp/node_modules/.npminstall/typings/1.3.0/typings, remove /home/taoqf/work/tmp/node_modules/.npminstall/typings-core/1.2.2/typings-core
error stack: JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)
headers: {"content-type":"text/plain; charset=utf-8","content-length":"21","date":"Fri, 17 Jun 2016 03:08:37 GMT","connection":"keep-alive"}
    at Object.parse (native)
    at parseJSON (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:745:24)
    at /home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:618:23
    at decodeContent (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:480:14)
    at IncomingMessage.<anonymous> (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:599:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[typings@1.3.0] install error: JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)
headers: {"content-type":"text/plain; charset=utf-8","content-length":"21","date":"Fri, 17 Jun 2016 03:08:37 GMT","connection":"keep-alive"}, parentDir: /home/taoqf/work/tmp, remove /home/taoqf/work/tmp/node_modules/.npminstall/typings/1.3.0/typings
error stack: JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)
headers: {"content-type":"text/plain; charset=utf-8","content-length":"21","date":"Fri, 17 Jun 2016 03:08:37 GMT","connection":"keep-alive"}
    at Object.parse (native)
    at parseJSON (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:745:24)
    at /home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:618:23
    at decodeContent (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:480:14)
    at IncomingMessage.<anonymous> (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:599:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)
headers: {"content-type":"text/plain; charset=utf-8","content-length":"21","date":"Fri, 17 Jun 2016 03:08:37 GMT","connection":"keep-alive"}
JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)
headers: {"content-type":"text/plain; charset=utf-8","content-length":"21","date":"Fri, 17 Jun 2016 03:08:37 GMT","connection":"keep-alive"}
    at Object.parse (native)
    at parseJSON (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:745:24)
    at /home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:618:23
    at decodeContent (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:480:14)
    at IncomingMessage.<anonymous> (/home/taoqf/.nvm/versions/node/v6.2.1/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:599:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
｀｀｀

**Comment by fengmk2** [comment]
`500 (connected: true, keepalive socket: true)` 你们的服务器500错误了。

**Comment by fengmk2** [comment]
> [form-data@0.2.0] install error: JSONResponseFormatError: Unexpected token I in JSON at position 0 (data json format: "Internal Server Error"), GET http://192.168.40.195:7001/async/%3E%3D0.9.0%20%3C0.10.0 500 (connected: true, keepalive socket: true)

**Comment by taoqf** [comment]
Can we solve this?

**Comment by fengmk2** [comment]
You need to checkout `http://192.168.40.195:7001` error log and find out what happen.
