### ISSUE TITLE
cnpm 安装 c++包，提示找不到 node-gyp

### ISSUE THREAD

**Issue by demohi** [cnpm/cnpm#123]
```
sh: 1: node-gyp: not found
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 127
Error: post install error, please remove node_modules before retry!
Run "sh -c node-gyp rebuild" error, exit code 127
    at ChildProcess.proc.on.code (/usr/lib/node_modules/cnpm/node_modules/runscript/index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

使用 npm 安装是好的

环境
系统：docker Ubuntu 14.04
node: v6.2.1
cnpm: v4.2.0
npm: v3.9.3

**Comment by dead-horse** [comment]
先装一个 node-gyp.  `cnpm insatll node-gyp -g`

**Comment by demohi** [comment]
多谢 @dead-horse  解决了
