### ISSUE TITLE
cnpm 下载的文件，哈希值不一致？

### ISSUE THREAD

**Issue by Loyalsoldier** [cnpm/cnpm#133]
用 [vue-cli](https://github.com/vuejs/vue-cli) 初始化了一个项目，然后 `cnpm install`，提示以下错误：

```
[selenium-server@2.53.0] download error: selenium-server@2.53.0 sha1:1aa1bdb4c3c74e71ddc3c4be15c6ea864727aa89 not equal to 95cdbe72acca687bb6a0b7fc9e3b8bf0c9c7bf2f (sel
enium-server@2.53.0), fail count: 3
ShasumNotMatchError: selenium-server@2.53.0 sha1:1aa1bdb4c3c74e71ddc3c4be15c6ea864727aa89 not equal to 95cdbe72acca687bb6a0b7fc9e3b8bf0c9c7bf2f (selenium-server@2.53.0)

ShasumNotMatchError: selenium-server@2.53.0 sha1:1aa1bdb4c3c74e71ddc3c4be15c6ea864727aa89 not equal to 95cdbe72acca687bb6a0b7fc9e3b8bf0c9c7bf2f (selenium-server@2.53.0)

    at ReadStream.<anonymous> (D:\dev\software\nodejs\node_global\node_modules\cnpm\node_modules\npminstall\lib\download\npm.js:249:21)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by dead-horse** [comment]
可以本地将 https://cdn.npm.taobao.org/selenium-server/-/selenium-server-2.53.0.tgz 这个文件下载下来算一下 shasum 出来是多少么？我在 mac 上算出来是正确的

**Comment by Loyalsoldier** [comment]
奇怪了，我这里也是 `95cdbe72acca687bb6a0b7fc9e3b8bf0c9c7bf2f`

**Comment by dead-horse** [comment]
重新下载一次试试呢？

**Comment by dead-horse** [comment]
重新安装

**Comment by Loyalsoldier** [comment]
关掉代理之后，重新初始化项目，清掉了 cnpm 缓存，重新 cnpm install……还是一样的错误，但是这次测出来的错误的 SHA1 跟上一次的错误的 SHA1 不一样。两者都不是正确的 SHA1

**Comment by fengmk2** [comment]
看来需要加上重试

**Comment by dead-horse** [comment]
有重试了。。。`fail count: 3
`

**Comment by fengmk2** [comment]
好吧，我将 headers 和 url 等都输出来。

**Comment by fengmk2** [comment]
@Loyalsoldier 你们上网是否有代理？感觉是在代理层的缓存坏了。

**Comment by Loyalsoldier** [comment]
第一次安装失败是开了 Shadowsocks 代理，第二次安装错误没有开代理。两次之间，用 npm cache clear 清楚过缓存

**Comment by Loyalsoldier** [comment]
刚刚又试了一次……开着代理和关掉代理，都安装成功了……

**Comment by fengmk2** [comment]
@Loyalsoldier 你试试 cnpm i --no-cache 去掉缓存看看。

**Comment by Loyalsoldier** [comment]
@fengmk2 现在一切正常……估计之前的错误是网络问题。

不过，虽然能安装成功，但是项目里面 `npm run dev` 并不能正常运行项目。不知道是不是某些插件的写法不标准？用 npm 安装的话，`npm run dev` 能正常运行项目。

**Comment by Loyalsoldier** [comment]
不知道下面这个错误跟这个问题有没有关系：

`cnpm install` 装好了项目依赖之后，`cnpm run dev` 会报错如下：

```
$ cnpm run dev

> get@1.0.0 dev D:\test\get
> node build/dev-server.js

Listening at http://localhost:8080

webpack built b7d2d313f0e7e0027328 in 1933ms
Hash: b7d2d313f0e7e0027328
Version: webpack 1.13.1
Time: 1933ms
 Asset    Size  Chunks       Chunk Names
app.js  275 kB       0       app

ERROR in ./src/main.js
Module build failed: Error: Failed to load plugin html: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at
https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at Object.<anonymous> (D:\test\get\node_modules\.eslint-plugin-html@1.5.1\src\index.js:42:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.module.exports.load (D:\test\get\node_modules\.eslint@2.13.1\lib\config\plugins.js:114:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (D:\test\get\node_modules\.eslint@2.13.1\lib\config\plugins.js:136:21)
    at Object.load (D:\test\get\node_modules\.eslint@2.13.1\lib\config\config-file.js:505:21)
    at loadConfig (D:\test\get\node_modules\.eslint@2.13.1\lib\config.js:64:33)
    at getLocalConfig (D:\test\get\node_modules\.eslint@2.13.1\lib\config.js:126:23)
    at Config.getConfig (D:\test\get\node_modules\.eslint@2.13.1\lib\config.js:227:22)
    at processText (D:\test\get\node_modules\.eslint@2.13.1\lib\cli-engine.js:223:27)
    at CLIEngine.executeOnText (D:\test\get\node_modules\.eslint@2.13.1\lib\cli-engine.js:761:26)
 @ multi app
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  21.4 kB       0
webpack: bundle is now VALID.
```

访问 `localhost:8080` 显示 `Cannot GET /`

系统环境：Windows 10 Pro 64bit，Git-for-windows 的 Git Bash 64bit

是 `eslint-plugin-html` 这个 package 不支持 cnpm？

**Comment by fengmk2** [comment]
@Loyalsoldier 重新安装 cnpm，然后重新来就 ok 了。

**Comment by Loyalsoldier** [comment]
我用的就是最新的 cnpm v4.3.1

**Comment by zhangmingze** [comment]
@Loyalsoldier 
cnpm v4.3.1
也遇到同样的问题了，这个怎么解决的？

**Comment by Loyalsoldier** [comment]
@zhangmingze 重新下载一遍试试？不行的话，我也没辙了……

我也不知道原因

**Comment by zhangmingze** [comment]
@Loyalsoldier 虽然出现哈希值错误，但是可以跑起来，没出问题，先不管了，可能是代理问题

**Comment by zcl20131002578** [comment]
额，我是先用的cnpm来装的，出现了一些哈希值不匹配的问题，然后我查了些资料，1：试一试清除缓存，但是无用 2：升级一下cnpm 也无用  最后小弟不才用npm装的，虽然有WARN但是安装成功了
