### ISSUE TITLE
node v0.12 下报错

### ISSUE THREAD

**Issue by gucong3000** [cnpm/cnpm#144]
```bash
cdyf@QIL:/mnt/e/work/gulp-postcss$
cdyf@QIL:/mnt/e/work/gulp-postcss$ nvm use 0.12
cNow using node v0.12.16 (npm v2.15.1)
cdyf@QIL:/mnt/e/work/gulp-postcss$ cnpm i
/usr/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js:5
const debug = require('debug')('npminstall:bin:install');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by dead-horse** [comment]
node 版本太低了，升级到 4.x 以上
