### ISSUE TITLE
Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by Ljzn** [cnpm/cnpm#151]
When `cnpm install`

```
ResponseError: Hostname/IP doesn't match certificate's altnames: "Host: cdn.npm.taobao.org. is not in the cert's altnames: DNS:*.oss-cn-hangzhou.aliyuncs.com, DNS:oss-cn-hangzhou.aliyuncs.com" (req "error"), GET https://cdn.npm.taobao.org/jquery/-/jquery-1.12.4.tgz -1 (connected: true, keepalive socket: false)
headers: {}, GET http://registry.npm.taobao.org/jquery/download/jquery-1.12.4.tgz -1 (connected: true, keepalive socket: false)
headers: {}
Error: Hostname/IP doesn't match certificate's altnames: "Host: cdn.npm.taobao.org. is not in the cert's altnames: DNS:*.oss-cn-hangzhou.aliyuncs.com, DNS:oss-cn-hangzhou.aliyuncs.com"
    at Object.checkServerIdentity (tls.js:199:15)
    at TLSSocket.<anonymous> (_tls_wrap.js:1066:29)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:584:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)
npminstall version: 2.0.2
npminstall args: /usr/local/Cellar/node/6.3.1/bin/node /usr/local/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/Users/zlj/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org
```

**Comment by renaesop** [comment]
同。 NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by topwood** [comment]
+1

**Comment by shevchenhe** [comment]
+1

**Comment by fallenner** [comment]
+10086

**Comment by surmind** [comment]
+1
淘宝的域名，阿里云的证书

**Comment by wahyd4** [comment]
+1

**Comment by Leighton0** [comment]
+1

**Comment by fengmk2** [comment]
证书出问题了，我先改成 http

**Comment by Sher9** [comment]
+1

**Comment by fengmk2** [comment]
已经切换到 http，大家再试试，看看是否还有问题？

**Comment by wahyd4** [comment]
成都已经可以正常下载了。 👍

**Comment by fallenner** [comment]
已经可以了

**Comment by fengmk2** [comment]
原因清楚了：cdn.npm.taobao.org CDN 欠费了，然后 CDN 自动域名解析到 OSS，导致使用 OSS 证书而提示错误了。

```bash
$ dig cdn.npm.taobao.org

;; ANSWER SECTION:
cdn.npm.taobao.org.	300	IN	CNAME	cdn.npm.taobao.org.w.kunlunar.com.
cdn.npm.taobao.org.w.kunlunar.com. 300 IN CNAME	tnpm-hz.oss-cn-hangzhou.aliyuncs.com.
tnpm-hz.oss-cn-hangzhou.aliyuncs.com. 60 IN A	120.27.176.37
```

**Comment by coder-huo** [comment]
阿里巴巴这个坑逼
