### ISSUE TITLE
[求助] ShasumNotMatchError

### ISSUE THREAD

**Issue by zzswang** [cnpm/cnpm#156]
求助 快被这个搞疯了。。。

如果我用 cnpm install --no-cache 是可以成功安装上的

所以看起来是 cache 有问题

那么如何清空 cnpm 的cache 呢？

是清本地的cache 还是 我搭的cnpmjs server上的cache。

多谢~~

PS：cnpm install 是放在building服务器上的，所以把 --no-chache 加上的话，临时解决一下可以，但以后是个大问题

```
⠦ Installing extsprintf@1.0.2[echarts@3.3.0] download ShasumNotMatchError: real sha1:21dd3e7b1b3601e33da3a6ef3cf2fe307b3b13ba not equal to remote:c310ab67e4b81a58e16b95f00babaa803f051c39 (echarts@3.3.0) (/root/.npminstall_tarball/e/c/h/a/echarts/3.3.0-c310ab67e4b81a58e16b95f00babaa803f051c39.tgz), fail count: 1
⠹ Installing vary@~1.1.0[echarts@3.3.0] download ShasumNotMatchError: real sha1:09445b2e1fc6c0d7661781b9b9bc5f7940111173 not equal to remote:c310ab67e4b81a58e16b95f00babaa803f051c39 (echarts@3.3.0) (/root/.npminstall_tarball/e/c/h/a/echarts/3.3.0-c310ab67e4b81a58e16b95f00babaa803f051c39.tgz), fail count: 2
⠴ Installing readable-stream@^1.0.27-1[caniuse-db@1.0.30000572] download ShasumNotMatchError: real sha1:adf86eb1e28de8a6a32baf414ed3dff1e578c1bb not equal to remote:81d0aa6b7de2d785c8dcab135502983276cc707d (caniuse-db@1.0.30000572) (/root/.npminstall_tarball/c/a/n/i/caniuse-db/1.0.30000572-81d0aa6b7de2d785c8dcab135502983276cc707d.tgz), fail count: 1
⠴ Installing readable-stream@^1.0.27-1[echarts@3.3.0] download ShasumNotMatchError: real sha1:6e2b3f2efb95a7997e30479d3ceb393aea4d6adc not equal to remote:c310ab67e4b81a58e16b95f00babaa803f051c39 (echarts@3.3.0) (/root/.npminstall_tarball/e/c/h/a/echarts/3.3.0-c310ab67e4b81a58e16b95f00babaa803f051c39.tgz), fail count: 3
ShasumNotMatchError: real sha1:6e2b3f2efb95a7997e30479d3ceb393aea4d6adc not equal to remote:c310ab67e4b81a58e16b95f00babaa803f051c39 (echarts@3.3.0) (/root/.npminstall_tarball/e/c/h/a/echarts/3.3.0-c310ab67e4b81a58e16b95f00babaa803f051c39.tgz)
    at ReadStream.readstream.on (/usr/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:384:21)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npminstall version: 2.9.5
npminstall args: /usr/bin/nodejs /usr/lib/node_modules/cnpm/node_modules/.bin/npminstall --china --userconfig=/root/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://localhost:7001
```

**Comment by fengmk2** [comment]
是不是你有多个 cnpm install 进程同时运行？

**Comment by fengmk2** [comment]
如果是，不能开启 local cache，因为目前没有做多进程文件缓存锁。

**Comment by zzswang** [comment]
应该只有一个 cnpm install，我只设置了一个 进程跑 build

**Comment by zzswang** [comment]
在本地跑 也会出一样的错误。其中echarts 这个包，是百度的图表库。

**Comment by zzswang** [comment]
我是本地搭了一个 cnpmjs 的服务器，放一些private的包

然后通过cnpm install

会不会是 cnpmjs 服务器的问题？

**Comment by fengmk2** [comment]
no-cache 不是成功的么？如果cnpmjs 服务器问题，no-cache 也会不成功才对的。

**Comment by zzswang** [comment]
对 no-cache 是成功的，有没有办法 清一下 cnpm 的cache ？

**Comment by fengmk2** [comment]
`rm -rf /root/.npminstall_tarball`

**Comment by zzswang** [comment]
通过 `rm -rf /root/.npminstall_tarball`   清了cache后，还是出在这个问题 

```
⠏ Installing echarts@^3.1.3[nyc@8.3.0] download ShasumNotMatchError: real sha1:60a0f241402c7d761ad0cd287b2699720596a891 not equal to remote:bb78fb0630bf93985f8143b73943b856aea0f0d1 (nyc@8.3.0) (/home/gitlab-runner/.npminstall_tarball/n/y/c/nyc/8.3.0-bb78fb0630bf93985f8143b73943b856aea0f0d1.tgz), fail count: 1
⠙ Installing echarts@^3.1.3[echarts@3.3.0] download ShasumNotMatchError: real sha1:1844d1d0ed67194a3a86f722c7716f398007de25 not equal to remote:c310ab67e4b81a58e16b95f00babaa803f051c39 (echarts@3.3.0) (/home/gitlab-runner/.npminstall_tarball/e/c/h/a/echarts/3.3.0-c310ab67e4b81a58e16b95f00babaa803f051c39.tgz), fail count: 1
⠹ Installing echarts@^3.1.3[echarts@3.3.0] download ShasumNotMatchError: real sha1:6dd53fc8d1cf67255c8c892cbaa9c695f3e80368 not equal to remote:c310ab67e4b81a58e16b95f00babaa803f051c39 (echarts@3.3.0) (/home/gitlab-runner/.npminstall_tarball/e/c/h/a/echarts/3.3.0-c310ab67e4b81a58e16b95f00babaa803f051c39.tgz), fail count: 2
⠇ Installing echarts@^3.1.3[nyc@8.3.0] download ShasumNotMatchError: real sha1:5bd2d1c9a198c2b667550bfeab19671a496f90d6 not equal to remote:bb78fb0630bf93985f8143b73943b856aea0f0d1 (nyc@8.3.0) (/home/gitlab-runner/.npminstall_tarball/n/y/c/nyc/8.3.0-bb78fb0630bf93985f8143b73943b856aea0f0d1.tgz), fail count: 2
```

**Comment by fengmk2** [comment]
@zzswang 你本地或者其他服务器是否也是这个问题？

**Comment by zzswang** [comment]
对 本地也有这个问题。

另外我再国外的机器上 用 `cnpm install`  好像就没有这个问题

cnpm 好像 会去直连 registry.npm.org

**Comment by fengmk2** [comment]
不会的，cnpm 默认是取 https://registry.npm.taobao.org 请求的。

**Comment by zzswang** [comment]
有一个相对完整的日志，里面有 显示从 nmpjs.org 请求数据

`GET https://registry.npmjs.com/expand-brackets/latest -1 (connected: true, keepalive socket: true)`

```
node-sass@3.8.0 installed at node_modules/.3.8.0@node-sass
[chokidar@^1.0.0] optional install error: ResponseTimeoutError: Response timeout for 60000ms, GET https://registry.npmjs.com/expand-brackets/latest -1 (connected: true, keepalive socket: true)
headers: {}
    at Timeout._onTimeout (/usr/local/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:715:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
reactstrap@2.0.0 installed at node_modules/.2.0.0@reactstrap
webpack@1.13.1 installed at node_modules/.1.13.1@webpack
[echarts@3.3.1] download ShasumNotMatchError: real sha1:6c672d3f53e073c5ccbf9af0d24fe56a57b57b9b not equal to remote:35ad7b1e9e941450ad3e0134635a04bf1e61bb42 (echarts@3.3.1) (/Users/wangjunhua/.npminstall_tarball/e/c/h/a/echarts/3.3.1-35ad7b1e9e941450ad3e0134635a04bf1e61bb42.tgz), fail count: 2
[echarts@3.3.1] download ShasumNotMatchError: real sha1:6bdccccf76f7ecd791359254054bdd6e22c000e7 not equal to remote:35ad7b1e9e941450ad3e0134635a04bf1e61bb42 (echarts@3.3.1) (/Users/wangjunhua/.npminstall_tarball/e/c/h/a/echarts/3.3.1-35ad7b1e9e941450ad3e0134635a04bf1e61bb42.tgz), fail count: 3
ShasumNotMatchError: real sha1:6bdccccf76f7ecd791359254054bdd6e22c000e7 not equal to remote:35ad7b1e9e941450ad3e0134635a04bf1e61bb42 (echarts@3.3.1) (/Users/wangjunhua/.npminstall_tarball/e/c/h/a/echarts/3.3.1-35ad7b1e9e941450ad3e0134635a04bf1e61bb42.tgz)
    at ReadStream.readstream.on (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:384:21)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npminstall version: 2.7.0
```

**Comment by fengmk2** [comment]
@zzswang 重现的方式发我一下，我看看为何会去请求。目前看日志就是 postinstall 里面调用了 npm install

**Comment by fengmk2** [comment]
npminstall version: 2.7.0

可以看到你的 cnpm 版本已经老了，重新安装一下 cnpm i -g cnpm

**Comment by zzswang** [comment]
我的 cnpm 是最新的，一直很奇怪，好像 npminstall 的版本就是涨不上去 ... 我马上试一下。 

下午，我把package.json 文件整理一下，发上来。

**Comment by zzswang** [comment]
今天怪事 特别多，执行 `cnpm install -g cnpm` 遇到这个错误

```
 ~  cnpm install -g cnpm                                                                                                          ✓  15:11:49 
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/Cellar/node/6.8.1/bin/npm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
 ~  sudo cnpm install -g cnpm                                                                                                   1 ↵  15:11:55 
Password:
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/Cellar/node/6.8.1/bin/npm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
 ~                                                                                                                              1 ↵  15:12:03 
```

**Comment by zzswang** [comment]
这个是摘出来的 package.json

```
{
  "name": "test",
  "version": "0.1.10",
  "description": "1222",
  "main": "./src/export",
  "scripts": {
    "build": "webpack --color --profile",
    "clear": "rm -rf dist",
    "deploy": "scp -r dist/*",
    "lint": "eslint src",
    "start": "babel-node bin/start.js",
    "test": "nyc --require babel-core/register mocha ./src/tests/**"
  },
  "repository": {
    "type": "git",
    "url": "git@github.com/saa.git"
  },
  "keywords": [
    "webpack",
    "browserSync",
    "react",
    "redux",
    "start",
    "quick",
    "example"
  ],
  "author": "test",
  "license": "ISC",
  "browser": {
    "joi": "joi-browser"
  },
  "devDependencies": {
    "babel-cli": "6.9.0",
    "babel-core": "6.9.1",
    "babel-eslint": "6.1.2",
    "babel-loader": "6.2.4",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-preset-es2015": "6.9.0",
    "babel-preset-react": "6.5.0",
    "babel-preset-react-hmre": "1.1.1",
    "babel-preset-stage-0": "6.5.0",
    "body-parser": "1.15.2",
    "browser-sync": "2.12.10",
    "chai": "3.5.0",
    "config": "^1.21.0",
    "connect-history-api-fallback": "1.2.0",
    "css-loader": "0.23.1",
    "eslint": "^3.3.1",
    "eslint-config-airbnb": "^10.0.1",
    "eslint-loader": "^1.4.1",
    "eslint-plugin-import": "^1.12.0",
    "eslint-plugin-jsx-a11y": "^2.0.1",
    "eslint-plugin-react": "^6.0.0",
    "exports-loader": "0.6.3",
    "express": "4.14.0",
    "express-jwt": "3.4.0",
    "extract-text-webpack-plugin": "1.0.1",
    "file-loader": "0.8.5",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "2.22.0",
    "http-proxy": "1.15.1",
    "imports-loader": "0.6.5",
    "jsonwebtoken": "7.1.9",
    "markdown-loader": "^0.1.7",
    "mocha": "3.0.2",
    "node-sass": "3.8.0",
    "nyc": "8.3.0",
    "react-hot-loader": "3.0.0-beta.2",
    "sass-loader": "3.2.0",
    "script-loader": "0.7.0",
    "should": "11.1.0",
    "style-loader": "0.13.1",
    "url-loader": "0.5.7",
    "webpack": "1.13.1",
    "webpack-dev-middleware": "1.6.1",
    "webpack-hot-middleware": "2.10.0"
  },
  "dependencies": {
    "babel-polyfill": "6.9.1",
    "bootstrap": "4.0.0-alpha.4",
    "classnames": "2.2.5",
    "dagre": "0.7.4",
    "dsv-loader": "1.0.3",
    "form-serialize": "0.7.1",
    "github-markdown-css": "2.4.0",
    "history": "3.0.0",
    "joi": "9.0.4",
    "joi-browser": "9.0.4",
    "js-base64": "2.1.9",
    "lodash": "4.14.1",
    "moment": "2.13.0",
    "rc-slider": "3.7.3",
    "react": "15.3.1",
    "react-addons-transition-group": "15.1.0",
    "react-addons-update": "15.1.0",
    "react-dom": "15.1.0",
    "react-echarts": "0.1.1",
    "react-redux": "4.4.5",
    "react-router": "3.0.0-alpha.3",
    "react-router-apply-middleware": "0.0.2",
    "react-select": "1.0.0-rc.1",
    "reactstrap": "2.0.0",
    "redux": "3.5.2",
    "redux-api-middleware": "1.0.2",
    "redux-logger": "2.6.1",
    "redux-thunk": "2.1.0"
  }
}
```

**Comment by zzswang** [comment]
cnpm install 不走控制台设置的 http_proxy 代理么?

**Comment by fengmk2** [comment]
都镜像了还走代理。。。为何？目前还没支持，依然在开发中。 https://github.com/node-modules/urllib/pull/226
