### ISSUE TITLE
uninstall的逻辑有点问题

### ISSUE THREAD

**Issue by leungwensen** [cnpm/cnpm#158]
在.npmrc文件里配置了 prefix，用cnpm install安装全局包的时候是正常的，但跑cnpm uninstall出错了。本应该删除 prefix (/mnt/e/nodejs/) 里的包，但到/usr/lib/node_modules/下去找了。具体见截图。npm uninstall是正常的。

我猜想是因为install的时候是调的npminstall命令，而uninstall则是用npm命令做的，而这两种做法不一定是match的。我不知道是不是需要到 cnpm/npminstall 项目下提个issue？

![image](https://cloud.githubusercontent.com/assets/1655789/20095199/84275460-a5df-11e6-8aa6-2aacf1a562c3.png)

环境： windows 10 WSL（ubuntu）:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

```
$ cnpm --version
4.4.0
$ npm --version
3.10.8
$ nodejs --version
v6.9.1
```

**Comment by fengmk2** [comment]
是个问题，应该使用 npmuninstall 才对。

**Comment by LichFaker** [comment]
遇到类似问题。 之前使用一直正常，执行了`cnpm uninstall` 后再次安装出现如下问题：
```
[npminstall:get] retry GET http://registry.npm.taobao.org/koa after 100ms, retry left 4, error: SyntaxError: Unexpected token < in JSON at position 0
⠙ [0/1] Installing koa@^2.3.0[npminstall:get] retry GET http://registry.npm.taobao.org/koa after 200ms, retry left 3, error: SyntaxError: Unexpected token < in JSON at position 0
⠼ [0/1] Installing koa@^2.3.0[npminstall:get] retry GET http://registry.npm.taobao.org/koa after 300ms, retry left 2, error: SyntaxError: Unexpected token < in JSON at position 0
⠇ [0/1] Installing koa@^2.3.0[npminstall:get] retry GET http://registry.npm.taobao.org/koa after 400ms, retry left 1, error: SyntaxError: Unexpected token < in JSON at position 0
✖ Install fail! SyntaxError: Unexpected token < in JSON at position 0
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at _get (/Users/lichfaker/.nvm/versions/node/v8.3.0/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:70:26)
    at _get.next (<anonymous>)
    at onFulfilled (/Users/lichfaker/.nvm/versions/node/v8.3.0/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npminstall version: 3.1.1
```
重新卸载安装cnpm也一直存在该问题

**Comment by fengmk2** [comment]
@wyfyyy818818 你的是网络问题，中午11点30 ～ 12点30 期间，数据库被打满，已经修复。

**Comment by liuyuchuans** [comment]
我也遇到了   cnpm npm    都不行  我得是mac  以为是权限的问题  谁知道不行
![image](https://user-images.githubusercontent.com/37658672/56470919-9e89d200-647e-11e9-8a4b-c1cfdabe4b12.png)  求大神帮忙看看
