### ISSUE TITLE
升级到node v7.1.0 后报错

### ISSUE THREAD

**Issue by gucong3000** [cnpm/cnpm#159]
```bash
λ node -v
v7.1.0

λ npm install -g cnpm --registry=https://registry.npm.taobao.org
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
C:\Users\cdyf\AppData\Roaming\npm\cnpm -> C:\Users\cdyf\AppData\Roaming\npm\node_modules\cnpm\bin\cnpm
C:\Users\cdyf\AppData\Roaming\npm
`-- cnpm@4.4.0

λ cnpm i
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at Console.warn (console.js:51:16)
    at process.on (internal/process/warning.js:21:17)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
```

**Comment by fengmk2** [comment]
run `npm install -g cnpm --registry=https://registry.npm.taobao.org` again.
