### ISSUE TITLE
每次执行 cnpm install 报错

### ISSUE THREAD

**Issue by lcat** [cnpm/cnpm#175]
服务器上每次执行`cnpm i`都会报错，本地是不会。后面测试了下服务器是可以获取到[https://registry.npmjs.org/binary-mirror-config](https://registry.npmjs.org/binary-mirror-config)

报错信息：

```shell
Get /binary-mirror-config/latest from https://registry.npm.taobao.org error: ConnectionTimeoutError: Connect timeout for 5000ms, GET https://registry.npmjs.org/binary-mirror-config/latest -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":4,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})
headers: {}
    at Timeout._onTimeout (/usr/local/lib/node_modules/cnpm/node_modules/urllib/lib/urllib.js:701:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

```shell 
uname -a 
## Linux 7e0901f9549d 4.4.39-moby #1 SMP Fri Dec 16 07:34:12 UTC 2016 x86_64 GNU/Linux

node -v ## 6.9.2

npm -v ## 3.10.9

cnpm -v ## 4.4.2
```

**Comment by singone** [comment]
相同的问题。

**Comment by fengmk2** [comment]
请帮忙执行一下这个名，看看返回的时间和 headers

```bash
time curl -v https://registry.npm.taobao.org/binary-mirror-config/latest
```

**Comment by singone** [comment]
![63d78305180c950cfa69ffc7b6cd142a](https://cloud.githubusercontent.com/assets/6127730/21762086/c3ed52ec-d691-11e6-9960-1b34ac28fc1b.jpg)

**Comment by alsotang** [comment]
`time curl -v https://registry.npm.taobao.org/binary-mirror-config/latest` 这一句我这里执行才 0.2s，广州的腾讯云机器

**Comment by fengmk2** [comment]
@singone 看来是网速问题，只能将超时时间设置再大一些了，我会修复的。

**Comment by lcat** [comment]
```
* Hostname was NOT found in DNS cache
*   Trying 114.55.80.225...
* Connected to registry.npm.taobao.org (114.55.80.225) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: C=CN; ST=ZheJiang; L=HangZhou; O=Alibaba (China) Technology Co., Ltd.; CN=npm.taobao.org
* 	 start date: 2016-05-09 05:17:44 GMT
* 	 expire date: 2017-05-10 05:17:44 GMT
* 	 subjectAltName: registry.npm.taobao.org matched
* 	 issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Organization Validation CA - SHA256 - G2
* 	 SSL certificate verify ok.
> GET /binary-mirror-config/latest HTTP/1.1
> User-Agent: curl/7.38.0
> Host: registry.npm.taobao.org
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 10 Jan 2017 05:47:13 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 6738
< Connection: keep-alive
< X-Current-Requests: 1
< ETag: "1a52-+7/pBY+k5tJDJfbBtK8hrQ"
< X-ReadTime: 23
<
...
real	0m5.672s
user	0m0.020s
sys	0m0.000s
```

**Comment by lcat** [comment]
应该不是cnpm问题，关了
