### ISSUE TITLE
请教 cnpm  install私有化失败

### ISSUE THREAD

**Issue by wenshan** [cnpm/cnpm#190]
环境：macOS
cnpm.org版本：2.19.2
备注: 上周一切正常，包括上周五都在正常使用中，本周一（今天出现上述问题）
错误提示：
```
wenshandeMacBook-Pro% cnpm install @gag/style --registry='http://npm.gag.cn:7001'
✖ Install fail! Error: GET http://r.cnpmjs.org/@gag/style/download/@gag/style-1.0.1.tgz response 404 status
Error: GET http://r.cnpmjs.org/@gag/style/download/@gag/style-1.0.1.tgz response 404 status
    at get (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/get.js:51:17)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/cnpm/node_modules/co/index.js:65:19)
npminstall version: 2.29.1
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --china --userconfig=/Users/hou/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=http://npm.gag.cn:7001 @gag/style
```

cnpmrc信息：

```
//registry.npm.taobao.org/:_password="Z29vYWdvb0BmMmUsd="
//registry.npm.taobao.org/:username=f2e
//registry.npm.taobao.org/:email=fe@gooagoo.com
//registry.npm.taobao.org/:always-auth=false
@gag:registry=http://npm.gag.cn:7001/
//192.168.150.222:7003/:_password="Z29vYWdvb0BmMmUsdssd="
//192.168.150.222:7003/:username=f2e
//192.168.150.222:7003/:email=fe@gooagoo.com
//192.168.150.222:7003/:always-auth=false
//npm.gag.cn:7001/:_password="Z29vYWdvb0BmMmUsdsd="
//npm.gag.cn:7001/:username=f2e
//npm.gag.cn:7001/:email=fe@gooagoo.com
//npm.gag.cn:7001/:always-auth=false
```

**Comment by pfdgithub** [comment]
请问是如何解决的，遇到了类似的问题。  
具体信息请看 https://github.com/cnpm/cnpm/issues/219#issuecomment-371042512

**Comment by pfdgithub** [comment]
找到原因了，详见 https://github.com/cnpm/cnpm/issues/219#issuecomment-371125038
