### ISSUE TITLE
Prune not work 

### ISSUE THREAD

**Issue by ImJoeHs** [cnpm/cnpm#203]
**Env**
```
node: v8.0.0
cnpm： v4.5.0
npm: v5.0.0
```

Dependences were install by cnpm.
I am trying to use `prune`, but `cnpm prune` unbuild all my dependences :
```
...
unbuild uglify-js@3.0.17
unbuild webpack@2.6.1
unbuild which@1.2.14
...
```
 `cnpm ls gulp` 
 `(gulp) invalid error: ENOENT: no such file or directory`

So I turn to `npm prune`: 
```
Unhandled rejection RangeError: Maximum call stack size exceeded8.0.0
    at Array.forEach (native)
    at exports.create (/home/joe/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/node.js:33:25)
    at /home/joe/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/home/joe/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/node.js:33:25)
    at /home/joe/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/node.js:36:14
    at Array.forEach (native)
    at exports.create (/home/joe/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install/node.js:33:25)
    at normalizeTree (/home/joe/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:377:5)
    at Array.forEach (native)
    at normalizeTree (/home/joe/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/home/joe/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)
    at normalizeTree (/home/joe/.nvm/versions/node/v8.0.0/lib/node_modules/npm/lib/install.js:379:19)
    at Array.forEach (native)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joe/.npm/_logs/2017-06-16T07_40_19_138Z-debug.log

```

Any idea? Hope for answers, thanks.

**Comment by fengmk2** [comment]
cnpm default install mode not support prune, because is using https://github.com/cnpm/npminstall instead of `npm install`.

If you want to use prune, please install with npm mode

```bash
cnpm i --by=npm
```

**Comment by ImJoeHs** [comment]
Got it, thanks! 
Maybe it should be mentioned in the doc?
