### ISSUE TITLE
如果包中含有c++扩展的话，用cnpm安装就会报错

### ISSUE THREAD

**Issue by yunnysunny** [cnpm/cnpm#209]
如果包中含有c++扩展的话，用cnpm安装就会报错，但是用npm安装就正常。
```
cnpm@4.5.0 (d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\parse_argv.js)
npm@3.10.10 (d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@6.9.2 (d:\Program Files\nodejs\node.exe)
npminstall@2.29.1 (d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=D:\Program Files\nodejs
win32 x64 10.0.15063
registry=https://registry.npm.taobao.org
```

**Comment by fengmk2** [comment]
能否将完整错误提示贴上来？

**Comment by yunnysunny** [comment]
J:\native>cnpm install int64-native
√ Installed 1 packages
√ Linked 2 latest versions

J:\native\node_modules\._int64-native@0.4.0@int64-native>node "d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" configure

J:\native\node_modules\._int64-native@0.4.0@int64-native>node "d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" build
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .NET Framework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了其他位置，请将其位置添加到系统路径中。 [J:\native\node_modules
\._int64-native@0.4.0@int64-native\build\binding.sl
n]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "d:\\Program Files\\nodejs\\node.exe" "d:\\Users\\sunny\\AppData\\Roaming\\nvm\\v6.9.2\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "build"
gyp ERR! cwd J:\native\node_modules\._int64-native@0.4.0@int64-native
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
× Install fail! Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp configure && node-gyp build" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp configure && node-gyp build" error, exit code 1
    at ChildProcess.proc.on.code (d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\runscript\index.js:65:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 2.29.1
npminstall args: d:\Program Files\nodejs\node.exe d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\sunny\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org int64-native



yunnysunny
 
发件人： fengmk2
发送时间： 2017-08-04 11:33
收件人： cnpm/cnpm
抄送： 白一梓; Author
主题： Re: [cnpm/cnpm] 如果包中含有c++扩展的话，用cnpm安装就会报错 (#209)
能否将完整错误提示贴上来？

**Comment by yunnysunny** [comment]
刚才的例子举的不恰当，我贴一个使用npm能够安装的例子：
```
{lamb} npm install lmdb-queue

> lmdb-queue@0.2.0 install J:\native\node_modules\lmdb-queue
> node-gyp rebuild


J:\native\node_modules\lmdb-queue {git}
{lamb} if not defined npm_config_node_gyp (node "d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  midl.c
  mdb.c
  win_delay_load_hook.cc
  lmdb.vcxproj -> J:\native\node_modules\lmdb-queue\build\Release\\lmdb.lib
  module.cc
  env.cc
  topic.cc
  consumer.cc
  producer.cc
  win_delay_load_hook.cc
     Creating library J:\native\node_modules\lmdb-queue\build\Release\lmdb-queue.lib and object J:\native\node_modules\lmdb-queue\build\Release\lmdb-queue.exp
  Generating code
j:\native\node_modules\lmdb-queue\deps\lmdb\mdb.c(1344): warning C4172: returning address of local variable or temporary: buf [J:\native\node_modules\lmdb-queue\build\lmdb-queue.vcxproj]
  Finished generating code
  lmdb-queue.vcxproj -> J:\native\node_modules\lmdb-queue\build\Release\\lmdb-queue.node
  lmdb-queue.vcxproj -> J:\native\node_modules\lmdb-queue\build\Release\lmdb-queue.pdb (Full PDB)
J:\native
`-- lmdb-queue@0.2.0
  +-- nan@2.6.2
  `-- nnu@0.1.7

npm WARN enoent ENOENT: no such file or directory, open 'J:\native\package.json'
npm WARN native No description
npm WARN native No repository field.
npm WARN native No README data
npm WARN native No license field.
```

**Comment by yunnysunny** [comment]
然后再举一个使用cnpm失败的例子
```
{lamb} cnpm install lmdb-queue
√ Installed 1 packages
√ Linked 2 latest versions

J:\native\node_modules\._lmdb-queue@0.2.0@lmdb-queue {git}
{lamb} node "d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
MSBUILD : error MSB3428: 未能加载 Visual C++ 组件“VCBuild.exe”。要解决此问题，1) 安装 .NET Framework 2.0 SDK；2) 安装 Microsoft Visual Studio 2005；或 3) 如果将该组件安装到了其他位置，请将其位置添加到系统路径中。 [J:\native\node_modules
\._lmdb-queue@0.2.0@lmdb-queue\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "d:\\Program Files\\nodejs\\node.exe" "d:\\Users\\sunny\\AppData\\Roaming\\nvm\\v6.9.2\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\node-gyp.js" "rebuild"
gyp ERR! cwd J:\native\node_modules\._lmdb-queue@0.2.0@lmdb-queue
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
× Install fail! Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\runscript\index.js:65:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npminstall version: 2.29.1
npminstall args: d:\Program Files\nodejs\node.exe d:\Users\sunny\AppData\Roaming\nvm\v6.9.2\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfig=C:\Users\sunny\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.npm.taobao.org lmdb-queue
```
