### ISSUE TITLE
建议node-sass所依赖的binding.node也走代理

### ISSUE THREAD

**Issue by cipchk** [cnpm/cnpm#230]
一种莫名的伤心：

![tim 20171107131026](https://user-images.githubusercontent.com/2987467/32478032-40eab73a-c3bd-11e7-8688-674f402b3881.png)

> 以上进度已经在内心礼拜很多次才换来的结果，不然早就：ETIMEDOUT

**Comment by fengmk2** [comment]
请使用 cnpm 新版本来安装，node-sass 早就代理来。

```bash
cnpm i node-sass
✔ Installed 1 packages
✔ Linked 71 latest versions
Downloading binary from https://npm.taobao.org/mirrors/node-sass/v4.6.0/darwin-x64-57_binding.node
Download complete
Binary saved to /Users/mk2/git/gitlab.alibaba-inc.com/egg/jar2proxy/node_modules/_node-sass@4.6.0@node-sass/vendor/darwin-x64-57/binding.node
Caching binary to /Users/mk2/.npminstall_tarball/node-sass/4.6.0/darwin-x64-57_binding.node
Binary found at /Users/mk2/git/gitlab.alibaba-inc.com/egg/jar2proxy/node_modules/_node-sass@4.6.0@node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
✔ Run 1 scripts
Recently updated (since 2017-10-31): 1 packages (detail see file /Users/mk2/git/gitlab.alibaba-inc.com/egg/jar2proxy/node_modules/.recently_updates.txt)
✔ All packages installed (48 packages installed from npm registry, used 34s, speed 14.83kB/s, json 72(133.47kB), tarball 364.27kB)
```

**Comment by cipchk** [comment]
@fengmk2 若是某个包体依赖了 `node-sass` 的情况下是不走代理的

**Comment by fengmk2** [comment]
@cipchk 请给出重现例子。

**Comment by cipchk** [comment]
@fengmk2 [package.json](https://github.com/cipchk/ng-alain/blob/master/package.json)

**Comment by fengmk2** [comment]
@cipchk 依旧是没有问题的，请确保你的 cnpm 版本升级到了最新版本。你执行一下 cnpm -v 看看结果？

```bash
cnpm -v
cnpm@5.1.1 (/__enclose_io_memfs__/node_modules/_cnpm@5.1.1@cnpm/lib/parse_argv.js)
npm@5.3.0 (/__enclose_io_memfs__/node_modules/_npm@5.3.0@npm/lib/npm.js)
node@8.2.1 (/Users/mk2/.cli/cnpm)
npminstall@3.1.1 (/__enclose_io_memfs__/node_modules/_npminstall@3.1.1@npminstall/lib/index.js)
prefix=/Users/mk2/npm-global 
darwin x64 16.7.0 
registry=http://registry.npm.taobao.org
```

![image](https://user-images.githubusercontent.com/156269/32529140-c5401980-c471-11e7-82b0-3336fc3fd0b2.png)

**Comment by cipchk** [comment]
@fengmk2 

```
cnpm@5.1.1 (C:\Users\asdf\AppData\Roaming\npm\node_modules\cnpm\lib\parse_argv.js)
npm@5.5.1 (C:\Users\asdf\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@8.5.0 (C:\Program Files\nodejs\node.exe)
npminstall@3.2.1 (C:\Users\asdf\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\asdf\AppData\Roaming\npm
win32 x64 10.0.15063
registry=http://registry.npm.taobao.org
```

我不确定是不是我命令行有问题，因为我采用的是：`cnpm install --by=npm`

一个比较完整的结果日志：

```
PS C:\Users\asdf\Desktop\work\ng-alain> cnpm install --by=npm
npm WARN deprecated @types/moment@2.13.0: This is a stub types definition for Moment (https://github.com/moment/moment).
 Moment provides its own type definitions, so you don't need @types/moment installed!
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> node-sass@4.6.0 install C:\Users\asdf\Desktop\work\ng-alain\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.6.0/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.6.0/win32-x64-57_binding.node":

connect ETIMEDOUT 54.231.72.83:443

Timed out whilst downloading the prebuilt binary

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> wd@1.4.1 install C:\Users\asdf\Desktop\work\ng-alain\node_modules\wd
> node scripts/build-browser-scripts


> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\asdf\Desktop\work\ng-alain\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js


> sauce-connect-launcher@1.2.3 postinstall C:\Users\asdf\Desktop\work\ng-alain\node_modules\sauce-connect-launcher
> node scripts/install.js || nodejs scripts/install.js


> node-sass@4.6.0 postinstall C:\Users\asdf\Desktop\work\ng-alain\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\asdf\Desktop\work\ng-alain\node_modules\node-gyp\bin\node-gyp.js reb
uild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\asdf\\Desktop\\work\\ng-alain\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb download using dist-url https://npm.taobao.org/mirrors/node
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\asdf\\Desktop\\work\\ng
-alain\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\asdf\\Desktop\\work\\ng-alain\\node_modules\\which\\w
hich.js:68:19)\n    at E (C:\\Users\\asdf\\Desktop\\work\\ng-alain\\node_modules\\which\\which.js:80:29)\n    at C:\\Use
rs\\asdf\\Desktop\\work\\ng-alain\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\asdf\\Desktop\\work\\ng-alain\
\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\asdf\\Desktop\\work\\ng-alain\\node_modules\\isexe\\windows.js:36
:5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\asdf\Desktop\work\ng-alain\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:153:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\asdf\\Desktop\\work\\ng-
alain\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\asdf\\Desktop\\work\\ng-alain\\node_modules\\which\\wh
ich.js:68:19)\n    at E (C:\\Users\\asdf\\Desktop\\work\\ng-alain\\node_modules\\which\\which.js:80:29)\n    at C:\\User
s\\asdf\\Desktop\\work\\ng-alain\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\asdf\\Desktop\\work\\ng-alain\\
node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\asdf\\Desktop\\work\\ng-alain\\node_modules\\isexe\\windows.js:36:
5\n    at FSReqWrap.oncomplete (fs.js:153:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python27\python.exe -c import platform; print(platform.python_version());
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:270:12)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:927:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:348:11)
gyp ERR! stack     at emitOne (events.js:115:13)
gyp ERR! stack     at Socket.emit (events.js:210:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:545:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\asdf\\Desktop\\work\\ng-alain\\node_modules\\node-gyp
\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\asdf\Desktop\work\ng-alain\node_modules\node-sass
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @schematics/angular@0.0.49 requires a peer of @angular-devkit/schematics@0.0.34 but none is installed. You must
 install peer dependencies yourself.
npm WARN ng-alain@0.1.2-beta.10 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.6.0 (node_modules\node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.6.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1322 packages in 139.965s
```

**Comment by fengmk2** [comment]
@cipchk 必然，你使用 npm 模式，我们是无法解决这种特殊代理模式的。这个已经超出 cnpm 的范围了。

cnpm install --by=npm 相当于 npm i --registry=https://registry.npm.taobao.org ，没有使用到 cnpm 的功能，只使用了 registry。

**Comment by cipchk** [comment]
了解，感谢解惑。
