### ISSUE TITLE
通过cnpm安装node_modules下的package.json路径与npm不一致，导致AngularCLI进行AOT编译失败

### ISSUE THREAD

**Issue by SmokingIce** [cnpm/cnpm#232]
目前在使用angular框架进行开发，用cnpm安装的angular包下package.json所放路径与npm安装的不一样。
package.json应该和模块目录在同一层级，但是cnpm会安装到模块目录下。
例如：
cnpm： node_modules\_@angular_core@5.0.1@@angular\core\package.json
npm：   node_modules\_@angular_core@5.0.1@@angular\package.json

这样的安装会在AngularCLI进行AOT编译的时候找不到package.json，进而导致编译失败。

ng build --prod
`95% emittingUnhandled rejection Error: ENOENT: no such file or directory, open 'F:\Projects\AngularProjects\Angular5.x\node_modules\_@angular_core@5.0.1@@angular\package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at LicenseExtractor.readPackageJson (F:\Projects\AngularProjects\Angular5.x\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:124:23)
    at LicenseExtractor.parsePackage (F:\Projects\AngularProjects\Angular5.x\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseExtractor.js:21:32)
    at ModuleProcessor.processPackage (F:\Projects\AngularProjects\Angular5.x\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:24:46)
    at ModuleProcessor.processFile (F:\Projects\AngularProjects\Angular5.x\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\ModuleProcessor.js:21:21)
    at moduleCallback (F:\Projects\AngularProjects\Angular5.x\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:80:61)
    at Set.forEach (<anonymous>)
    at Chunk.forEachModule (F:\Projects\AngularProjects\Angular5.x\node_modules\_webpack@3.8.1@webpack\lib\Chunk.js:159:17)
    at F:\Projects\AngularProjects\Angular5.x\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:89:27
    at Array.forEach (<anonymous>)
    at Compiler.<anonymous> (F:\Projects\AngularProjects\Angular5.x\node_modules\_license-webpack-plugin@1.1.1@license-webpack-plugin\dist\LicenseWebpackPlugin.js:65:32)
    at next (F:\Projects\AngularProjects\Angular5.x\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:204:14)
    at F:\Projects\AngularProjects\Angular5.x\node_modules\_html-webpack-plugin@2.30.1@html-webpack-plugin\index.js:204:9
    at PassThroughHandlerContext.finallyHandler (F:\Projects\AngularProjects\Angular5.x\node_modules\_bluebird@3.5.1@bluebird\js\release\finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (F:\Projects\AngularProjects\Angular5.x\node_modules\_bluebird@3.5.1@bluebird\js\release\util.js:16:23)`

**Comment by alvachien** [comment]
Same issue

**Comment by jacky0karl** [comment]
请问怎么解决的呢？难道要手动拷贝到所有文件夹吗

**Comment by zxmsdyz** [comment]
也是同样的问题  难道必须用npm了

**Comment by oushu1tangxiangyue1** [comment]
same issue，目前换回npm了
