### ISSUE TITLE
上传包失败

### ISSUE THREAD

**Issue by lliuxp** [cnpm/cnpm#319]
2020-03-09 20:32:29.175 nodejs.ErrorException: Error: request entity too large
    at makeError (/root/cnpmjs.org/node_modules/raw-body/index.js:142:15)
    at /root/cnpmjs.org/node_modules/raw-body/index.js:38:17
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
pid: 18788
Host: izbp1fu4aeb6g5q3zqizpnz
URL: /
Data: ''
2020-03-09 20:32:29.175

**Comment by atian25** [comment]
错误信息写的很清楚了

**Comment by lliuxp** [comment]
> 错误信息写的很清楚了

可以调整限制么 ？

**Comment by lliuxp** [comment]
@atian25    可以调限制么？

**Comment by atian25** [comment]
看文档啊，文档都有写的

**Comment by atian25** [comment]
https://eggjs.github.io/zh/guide/upload.html#%E6%96%87%E4%BB%B6%E5%A4%A7%E5%B0%8F
