### ISSUE TITLE
UnzipError: incorrect data check

### ISSUE THREAD

**Issue by rcl4444** [cnpm/cnpm#331]
- env
cnpm@6.1.0 (C:\Users\GVT\AppData\Roaming\npm\node_modules\cnpm\lib\parse_argv.js)
npm@6.10.0 (C:\Users\GVT\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@8.12.0 (D:\Program Files\nodejs\node.exe)
npminstall@3.22.1 (C:\Users\GVT\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\GVT\AppData\Roaming\npm
win32 x64 10.0.17763
registry=https://r.npm.taobao.org
- error info
```
- [9/40] Installing babylon@^6.18.0[npminstall:get] retry GET https://r.npm.taobao.org/webpack after 100ms, retry left 4, error: UnzipError: incorrect data check, GET https://r.npm.taobao.org/webpack 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":11,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":43,"freeSockets":{"r.npm.taobao.org:443:::::::::":1,"r.npm.taobao.org:443:::::::true::":10},"sockets":{},"requests":{}}, socketHandledRequests: 3, socketHandledResponses: 3)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun8.cn462[3,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"57","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529c16052315759058448e"}, status: 200, headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun8.cn462[3,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"57","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529c16052315759058448e"},
stack: UnzipError: incorrect data check, GET https://r.npm.taobao.org/webpack 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":11,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":43,"freeSockets":{"r.npm.taobao.org:443:::::::::":1,"r.npm.taobao.org:443:::::::true::":10},"sockets":{},"requests":{}}, socketHandledRequests: 3, socketHandledResponses: 3)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun8.cn462[3,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"57","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529c16052315759058448e"}
    at Unzip.zlibOnError (zlib.js:153:15)
/ [9/40] Installing regenerator-runtime@^0.10.5[npminstall:get] retry GET https://r.npm.taobao.org/webpack after 200ms, retry left 3, error: UnzipError: incorrect data check, GET https://r.npm.taobao.org/webpack 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":11,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":55,"freeSockets":{"r.npm.taobao.org:443:::::::::":1,"r.npm.taobao.org:443:::::::true::":9},"sockets":{"r.npm.taobao.org:443:::::::true::":1},"requests":{}}, socketHandledRequests: 5, socketHandledResponses: 5)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun10.cn462[1,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"59","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529e16052315772134557e"}, status: 200, headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun10.cn462[1,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"59","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529e16052315772134557e"},
stack: UnzipError: incorrect data check, GET https://r.npm.taobao.org/webpack 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":11,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":55,"freeSockets":{"r.npm.taobao.org:443:::::::::":1,"r.npm.taobao.org:443:::::::true::":9},"sockets":{"r.npm.taobao.org:443:::::::true::":1},"requests":{}}, socketHandledRequests: 5, socketHandledResponses: 5)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun10.cn462[1,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"59","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529e16052315772134557e"}
    at Unzip.zlibOnError (zlib.js:153:15)
/ [9/40] Installing safe-buffer@~5.1.1[npminstall:get] retry GET https://r.npm.taobao.org/webpack after 300ms, retry left 2, error: UnzipError: incorrect data check, GET https://r.npm.taobao.org/webpack 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":11,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":75,"freeSockets":{"r.npm.taobao.org:443:::::::::":1,"r.npm.taobao.org:443:::::::true::":10},"sockets":{},"requests":{}}, socketHandledRequests: 7, socketHandledResponses: 7)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun10.cn462[1,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"60","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529e16052315781936492e"}, status: 200, headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun10.cn462[1,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"60","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529e16052315781936492e"},
stack: UnzipError: incorrect data check, GET https://r.npm.taobao.org/webpack 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":11,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":75,"freeSockets":{"r.npm.taobao.org:443:::::::::":1,"r.npm.taobao.org:443:::::::true::":10},"sockets":{},"requests":{}}, socketHandledRequests: 7, socketHandledResponses: 7)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun10.cn462[1,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"60","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529e16052315781936492e"}
    at Unzip.zlibOnError (zlib.js:153:15)
| [9/40] Installing lodash@^4.17.4[npminstall:get] retry GET https://r.npm.taobao.org/webpack after 400ms, retry left 1, error: UnzipError: incorrect data check, GET https://r.npm.taobao.org/webpack 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":11,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":79,"freeSockets":{"r.npm.taobao.org:443:::::::::":1,"r.npm.taobao.org:443:::::::true::":10},"sockets":{},"requests":{}}, socketHandledRequests: 8, socketHandledResponses: 8)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun5.cn462[2,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"61","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529916052315798433009e"}, status: 200, headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun5.cn462[2,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"61","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529916052315798433009e"},
stack: UnzipError: incorrect data check, GET https://r.npm.taobao.org/webpack 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":11,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":79,"freeSockets":{"r.npm.taobao.org:443:::::::::":1,"r.npm.taobao.org:443:::::::true::":10},"sockets":{},"requests":{}}, socketHandledRequests: 8, socketHandledResponses: 8)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun5.cn462[2,0]","content-encoding":"gzip","ali-swift-global-savetime":"1604554919","age":"61","x-cache":"HIT TCP_MEM_HIT dirn:0:127900397","x-swift-savetime":"Fri, 13 Nov 2020 01:38:38 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529916052315798433009e"}
    at Unzip.zlibOnError (zlib.js:153:15)
× Install fail! UnzipError: incorrect data check, GET https://r.npm.taobao.org/webpack 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":11,"createSocketErrorCo
unt":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":83,"freeSockets":{"r.npm.taobao.org:443:::::::::":1,"r.npm.taobao.org:443:::::::true::":8},"sockets":{"r.npm.taobao.org:443:::::::true::":2},"requests":{}}, socketHandledRequests: 8, socketHandledResponses: 8)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"70368","connection":"keep-alive","date":"Fri, 13 Nov 2020 01:38:38 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"79d846718cfeefb49d984ee27951e77a\"","x-hit-cache":"list-webpack-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"20","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache33.l2cn1801, izbp11dsagbzylz6yon5vtz, cache33.l2cn1801[41,304-0,M], cache5.l2cn1801[41,0], kunlun10.cn462[0,200-0,H], kunlun1.cn462[0,0]","con
```
- describe
当我使用npm install时无任何异常.

**Comment by wuzhaozhongguo** [comment]
我今天也出现了这个问题，昨天还好着，今天早上突然打包不了了
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)

**Comment by jackyli1991** [comment]
我今天也出现同样的问题，昨天还是好好的

**Comment by wuzhaozhongguo** [comment]
谁能修复下这个问题，或者告诉一下这个问题引起的原因

**Comment by qiqiboy** [comment]
@afc163 @fengmk2 pls

**Comment by hardmanhong** [comment]
同样出现问题，昨天还可以安装，今天就不行了
```
UnzipError: invalid distance too far back, GET https://r.npm.taobao.org/is-typedarray 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":11,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":378,"freeSockets":{"r.npm.taobao.org:443::::::::::::::::::":1,"r.npm.taobao.org:443::::::::true::::::::::":8},"sockets":{"r.npm.taobao.org:443::::::::true::::::::::":2},"requests":{}}, socketHandledRequests: 27, socketHandledResponses: 27)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"374","connection":"keep-alive","date":"Fri, 13 Nov 2020 08:17:34 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"2dd278432a90c4c144b2a2e90bffd52d\"","x-hit-cache":"list-is-typedarray-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"1","via":"cn462.l1, kunlun10.cn462, l2cn1801.l2, cache23.l2cn1801, izbp11dsagbzylz6yon5vtz, cache23.l2cn1801[23,304-0,M], cache19.l2cn1801[25,0], kunlun10.cn462[0,200-0,H], kunlun8.cn462[2,0]","content-encoding":"gzip","ali-swift-global-savetime":"1599054325","age":"9","x-cache":"HIT TCP_MEM_HIT dirn:10:833449779","x-swift-savetime":"Fri, 13 Nov 2020 08:17:34 GMT","x-swift-cachetime":"120","timing-allow-origin":"*","eagleid":"b739529c16052554636115890e"}
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
npminstall version: 3.25.0
npminstall args: /usr/bin/node /usr/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/var/lib/jenkins/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org
```

**Comment by LittleboyHarry** [comment]
同样抛锚了~只能借助 nrm 手动更换 npm 源临时用一用了。

**Comment by winterfree** [comment]
淘宝镜像的网站为什么突然挂了，点进去就是500页面

**Comment by wuzhaozhongguo** [comment]
官网怎么也挂了，没人管吗。

**Comment by wuzhaozhongguo** [comment]
又挂了，cnpm是不是不维护了
