### ISSUE TITLE
nuxt.js 项目 cnpm install 报错

### ISSUE THREAD

**Issue by 1014156094** [cnpm/cnpm#333]
![image](https://user-images.githubusercontent.com/16074662/100226180-54ba7500-2f5a-11eb-8d61-6b5bcfa1d7ac.png)
/ [5/20] Installing @babel/core@^7.12.0platform unsupported nuxt@2.14.7 › @nuxt/builder@2.14.7 › chokidar@3.4.3 › fsevents@~2.1.2 Package require os(darwin) not compatible with your platform(win32)
| [5/20] Installing ini@^1.3.5[fsevents@~2.1.2] optional install error: Package require os(darwin) not compatible with your platform(win32)
\ [11/20] Installing xtend@^4.0.0platform unsupported nuxt@2.14.7 › @nuxt/webpack@2.14.7 › cache-loader@4.1.0 › webpack@4.44.2 › watchpack@1.7.5 › watchpack-chokidar2@2.0.1 › chokidar@2.1.8 › fsevents@^1.2.7 Package 
require os(darwin) not compatible with your platform(win32)
\ [11/20] Installing xtend@^4.0.0[fsevents@^1.2.7] optional install error: Package require os(darwin) not compatible with your platform(win32)
\ [17/20] Installing type-is@~1.6.17[npminstall:get] retry GET https://r.npm.taobao.org/is-typedarray after 100ms, retry left 4, error: Error: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17) {
  errno: -3,
  code: 'Z_DATA_ERROR',
  name: 'UnzipError',
  data: <Buffer 1f 8b 08 00 00 00 00 00 00 03 bd 51 cb 4e eb 30 10 fd 17 af 9b d4 93 38 b6 93 35 7f 00 2b 16 a0 49 ec 34 16 89 1d d9 06 54 50 ff 9d 49 8b 80 2e 90 ee ... 324 more bytes>,
  path: '/is-typedarray',
  status: 200,
  headers: [Object],
  res: [Object]
}, status: 200, headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"374","connection":"keep-alive","date":"Wed, 25 Nov 2020 11:51:17 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"2dd278432a90c4c144b2a2e90bffd52d\"","x-hit-cache":"list-is-typedarray-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"1","via":"cn1585.l1, kunlun3.cn1585, l2cn2639.l2, cache66.l2cn2639, izbp17djxs02ot6ppjbt2jz, cache66.l2cn2639[0,304-0,H], cache36.l2cn2639[1,0], kunlun10.cn462[0,200-0,H], kunlun2.cn462[2,0]","x-swift-error":"forward peer connect close","content-encoding":"gzip","ali-swift-global-savetime":"1599054325","age":"48","x-cache":"HIT TCP_MEM_HIT dirn:11:465158752","x-swift-savetime":"Wed, 25 Nov 2020 11:51:43 GMT","x-swift-cachetime":"94","timing-allow-origin":"*","eagleid":"b739529616063051258403629e"},
stack: Error: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
| [17/20] Installing is-typedarray@~1.0.0[npminstall:get] retry GET https://r.npm.taobao.org/is-typedarray after 200ms, retry left 3, error: Error: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17) {
  errno: -3,
  code: 'Z_DATA_ERROR',
  name: 'UnzipError',
  data: <Buffer 1f 8b 08 00 00 00 00 00 00 03 bd 51 cb 4e eb 30 10 fd 17 af 9b d4 93 38 b6 93 35 7f 00 2b 16 a0 49 ec 34 16 89 1d d9 06 54 50 ff 9d 49 8b 80 2e 90 ee ... 324 more bytes>,
  path: '/is-typedarray',
  status: 200,
  headers: [Object],
  res: [Object]
}, status: 200, headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"374","connection":"keep-alive","date":"Wed, 25 Nov 2020 11:51:17 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"2dd278432a90c4c144b2a2e90bffd52d\"","x-hit-cache":"list-is-typedarray-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"1","via":"cn1585.l1, kunlun3.cn1585, l2cn2639.l2, cache66.l2cn2639, izbp17djxs02ot6ppjbt2jz, cache66.l2cn2639[0,304-0,H], cache36.l2cn2639[1,0], kunlun10.cn462[0,200-0,H], kunlun8.cn462[5,0]","x-swift-error":"forward peer connect close","content-encoding":"gzip","ali-swift-global-savetime":"1599054325","age":"48","x-cache":"HIT TCP_MEM_HIT dirn:11:465158752","x-swift-savetime":"Wed, 25 Nov 2020 11:51:43 GMT","x-swift-cachetime":"94","timing-allow-origin":"*","eagleid":"b739529c16063051259858949e"},
stack: Error: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
- [17/20] Installing source-map@^0.4.2[npminstall:get] retry GET https://r.npm.taobao.org/is-typedarray after 300ms, retry left 2, error: Error: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17) {
  errno: -3,
  code: 'Z_DATA_ERROR',
  name: 'UnzipError',
  data: <Buffer 1f 8b 08 00 00 00 00 00 00 03 bd 51 cb 4e eb 30 10 fd 17 af 9b d4 93 38 b6 93 35 7f 00 2b 16 a0 49 ec 34 16 89 1d d9 06 54 50 ff 9d 49 8b 80 2e 90 ee ... 324 more bytes>,
  path: '/is-typedarray',
  status: 200,
  headers: [Object],
  res: [Object]
}, status: 200, headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"374","connection":"keep-alive","date":"Wed, 25 Nov 2020 11:51:17 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"2dd278432a90c4c144b2a2e90bffd52d\"","x-hit-cache":"list-is-typedarray-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"1","via":"cn1585.l1, kunlun3.cn1585, l2cn2639.l2, cache66.l2cn2639, izbp17djxs02ot6ppjbt2jz, cache66.l2cn2639[0,304-0,H], cache36.l2cn2639[1,0], kunlun10.cn462[0,200-0,H], kunlun1.cn462[2,0]","x-swift-error":"forward peer connect close","content-encoding":"gzip","ali-swift-global-savetime":"1599054325","age":"49","x-cache":"HIT TCP_MEM_HIT dirn:11:465158752","x-swift-savetime":"Wed, 25 Nov 2020 11:51:43 GMT","x-swift-cachetime":"94","timing-allow-origin":"*","eagleid":"b739529516063051262317667e"},
stack: Error: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
- [17/20] Installing strip-bom@^2.0.0[npminstall:get] retry GET https://r.npm.taobao.org/is-typedarray after 400ms, retry left 1, error: Error: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17) {
  errno: -3,
  code: 'Z_DATA_ERROR',
  name: 'UnzipError',
  data: <Buffer 1f 8b 08 00 00 00 00 00 00 03 bd 51 cb 4e eb 30 10 fd 17 af 9b d4 93 38 b6 93 35 7f 00 2b 16 a0 49 ec 34 16 89 1d d9 06 54 50 ff 9d 49 8b 80 2e 90 ee ... 324 more bytes>,
  path: '/is-typedarray',
  status: 200,
  headers: [Object],
  res: [Object]
}, status: 200, headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"374","connection":"keep-alive","date":"Wed, 25 Nov 2020 11:51:17 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"2dd278432a90c4c144b2a2e90bffd52d\"","x-hit-cache":"list-is-typedarray-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"1","via":"cn1585.l1, kunlun3.cn1585, l2cn2639.l2, cache66.l2cn2639, izbp17djxs02ot6ppjbt2jz, cache66.l2cn2639[0,304-0,H], cache36.l2cn2639[1,0], kunlun10.cn462[0,200-0,H], kunlun7.cn462[1,0]","x-swift-error":"forward peer connect close","content-encoding":"gzip","ali-swift-global-savetime":"1599054325","age":"49","x-cache":"HIT TCP_MEM_HIT dirn:11:465158752","x-swift-savetime":"Wed, 25 Nov 2020 11:51:43 GMT","x-swift-cachetime":"94","timing-allow-origin":"*","eagleid":"b739529b16063051265714668e"},
stack: Error: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
× Install fail! UnzipError: invalid distance too far back, GET https://r.npm.taobao.org/is-typedarray 200 (connected: true, keepalive socket: true, agent status: {"createSocketCount":20,"createSocketErrorCount":0,"closeSocketCount":11,"errorSocketCount":0,"timeoutSocketCount":1,"requestCount":1052,"freeSockets":{"r.npm.taobao.org:443::::::::true::::::::::":9},"sockets":{},"requests":{}}, socketHandledRequests: 20, socketHandledResponses: 20)
headers: {"server":"Tengine","content-type":"application/json; charset=utf-8","content-length":"374","connection":"keep-alive","date":"Wed, 25 Nov 2020 11:51:17 GMT","x-current-requests":"1","vary":"accept, accept-encoding","etag":"W/\"2dd278432a90c4c144b2a2e90bffd52d\"","x-hit-cache":"list-is-typedarray-v1","cache-control":"max-age=0, s-maxage=120, must-revalidate","x-readtime":"1","via":"cn1585.l1, kunlun3.cn1585, l2cn2639.l2, cache66.l2cn2639, izbp17djxs02ot6ppjbt2jz, cache66.l2cn2639[0,304-0,H], cache36.l2cn2639[1,0], kunlun10.cn462[0,200-0,H], kunlun2.cn462[1,0]","x-swift-error":"forward peer connect close","content-encoding":"gzip","ali-swift-global-savetime":"1599054325","age":"50","x-cache":"HIT TCP_MEM_HIT dirn:11:465158752","x-swift-savetime":"Wed, 25 Nov 2020 11:51:43 GMT","x-swift-cachetime":"94","timing-allow-origin":"*","eagleid":"b739529616063051272866644e"}
Error: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:182:17)
npminstall version: 3.28.0
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\222\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\222\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org

**Comment by gongran** [comment]
我也遇到了这个问题

**Comment by atian25** [comment]
多重试下，换个网络看看。

如果还不行的话，试着升级下 zlib 和 node 的版本，根据关键词搜到一些它们的兼容性反馈

https://stackoverflow.com/questions/60288671/npm-install-on-synology-gives-zlib-invalid-distance-error

https://github.com/nodejs/node/issues/22839#issuecomment-474484250

**Comment by 1014156094** [comment]
npm install 是可以正常安装的，cnpm install 不行

**Comment by doneself** [comment]
我也是同样的问题，npm能安装，但是cnpm就报这个错。

**Comment by l619534951** [comment]
ant-design-vue的项目，用cnpm百分百会出问题，npm就不会，还是换回来了，好舍不得cnpm的安装速度。
