### ISSUE TITLE
Can't find package @dcloudio/uni-mp-360's version: 2.0.1-33920220207001

### ISSUE THREAD

**Issue by a526672351** [cnpm/cnpm#362]
✖ Install fail! Error: [@dcloudio/uni-mp-360@^2.0.1-33520211229002] Can't find package @dcloudio/uni-mp-360's version: 2.0.1-33920220207001
Error: [@dcloudio/uni-mp-360@^2.0.1-33520211229002] Can't find package @dcloudio/uni-mp-360's version: 2.0.1-33920220207001
    at resolve (/data/app/node-v14.18.2/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:99:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/data/app/node-v14.18.2/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:22:19)
    at async module.exports (/data/app/node-v14.18.2/lib/node_modules/cnpm/node_modules/npminstall/lib/download/index.js:21:10)
    at async _install (/data/app/node-v14.18.2/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:125:16)
    at async install (/data/app/node-v14.18.2/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:26:12)
    at async installOne (/data/app/node-v14.18.2/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:210:15)
    at async mapper (/data/app/node-v14.18.2/lib/node_modules/cnpm/node_modules/npminstall/lib/local_install.js:149:5)
npminstall version: 5.4.1
npminstall args: /data/app/node-v14.18.2/bin/node /data/app/node-v14.18.2/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/home/fhh/.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com

<img width="1071" alt="b1cac86bcfbb17ecbc7a7f85654ef07" src="https://user-images.githubusercontent.com/5345266/153536344-5e05699e-bb8b-47b6-af98-cdaa287e03cc.png">
<img width="653" alt="e9ba78cc290e065978489dc8169e291" src="https://user-images.githubusercontent.com/5345266/153536237-66118b86-223e-40e2-a570-3dcf286f5147.png">
<img width="516" alt="3eb413a29a6e0d81593d36b17160b53" src="https://user-images.githubusercontent.com/5345266/153536248-e75db9fe-eb63-44b0-b0f7-2653a3e462c9.png">

**Comment by fengmk2** [comment]
精简请求的数据没有同步导致的。我先刷新一下缓存。

curl -v https://registry.npmmirror.com/@dcloudio%2Funi-mp-360 > foo -H 'Accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.9, */*'

**Comment by fengmk2** [comment]
fixed
