### ISSUE TITLE
升级cnpm8.2.0 后构建失败

### ISSUE THREAD

**Issue by lbftime** [cnpm/cnpm#383]
```
+ cnpm i
internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /data/env/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_13/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/data/env/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_13/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js:10:12)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/env/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_13/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js'
  ]
}
```

更新cnpm到 8.2.0 报以下错误，把cnpm恢复到7.1.1以后错误就没有了。

**Comment by lbftime** [comment]
问题已经解决，由于新的8.1.0后需要node14支持，导致无法构建，目前降级回7.1.1后正常。

**Comment by fengmk2** [comment]
请升级到 node >=14.x
