### ISSUE TITLE
 ResponseError: read ECONNRESET, GET https://cdn.npmmirror.com/packages/lottie-web/5.9.4/lottie-web-5.9.4.tgz 

### ISSUE THREAD

**Issue by ckelsel** [cnpm/cnpm#386]
```
root@f53a5b7eaaaa:/nuxt-sns# cnpm install
⠦ [15/76] Installing uuid@^3.1.0[npminstall:get] retry GET https://registry.npmmirror.com/lottie-web/-/lottie-web-5.9.4.tgz after 100ms, retry left 4, ResponseError: read ECONNRESET, GET https://cdn.npmmirror.com/packages/lottie-web/5.9.4/lottie-web-5.9.4.tgz -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":21,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":1,"timeoutSocketCount":0,"requestCount":254,"freeSockets":{"registry.npmmirror.com:443:::::::::::::::::::::":1},"sockets":{"registry.npmmirror.com:443::::::::true:::::::::::::":10,"cdn.npmmirror.com:443::::::::true:::::::::::::":10},"requests":{"registry.npmmirror.com:443::::::::true:::::::::::::":98,"cdn.npmmirror.com:443::::::::true:::::::::::::":35}}, socketHandledRequests: 2, socketHandledResponses: 2)
headers: {}, status: -1, headers: {}
[urllib:warn] [Wed Jun 08 2022 08:53:26 GMT+0000 (Coordinated Universal Time)] [176] [worker:431] GET https://cdn.npmmirror.com/packages/lottie-web/5.9.4/lottie-web-5.9.4.tgz callback twice!!!
[urllib:warn] [Wed Jun 08 2022 08:53:26 GMT+0000 (Coordinated Universal Time)] [176] [worker:431] Error: premature close
stack: Error: premature close
    at onclosenexttick (/usr/local/lib/node_modules/cnpm/node_modules/end-of-stream/index.js:53:86)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
⠹ [20/76] Installing eslint@^5.0.1[npminstall:get] retry GET https://registry.npmmirror.com/echarts/-/echarts-5.3.2.tgz after 100ms, retry left 4, ResponseError: read ECONNRESET, GET https://cdn.npmmirror.com/packages/echarts/5.3.2/echarts-5.3.2.tgz -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":22,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":2,"timeoutSocketCount":0,"requestCount":308,"freeSockets":{"registry.npmmirror.com:443:::::::::::::::::::::":1},"sockets":{"registry.npmmirror.com:443::::::::true:::::::::::::":10,"cdn.npmmirror.com:443::::::::true:::::::::::::":10},"requests":{"registry.npmmirror.com:443::::::::true:::::::::::::":107,"cdn.npmmirror.com:443::::::::true:::::::::::::":42}}, socketHandledRequests: 3, socketHandledResponses: 3)
headers: {}, status: -1, headers: {}
⠸ [20/76] Installing eslint@^5.0.1[urllib:warn] [Wed Jun 08 2022 08:53:27 GMT+0000 (Coordinated Universal Time)] [174] [worker:431] GET https://cdn.npmmirror.com/packages/echarts/5.3.2/echarts-5.3.2.tgz callback twice!!!
[urllib:warn] [Wed Jun 08 2022 08:53:27 GMT+0000 (Coordinated Universal Time)] [174] [worker:431] Error: premature close
stack: Error: premature close
    at onclosenexttick (/usr/local/lib/node_modules/cnpm/node_modules/end-of-stream/index.js:53:86)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

多执行几次 cnpm install最终能下载完成，能不能设置retry的次数，

**Comment by fengmk2** [comment]
可以关注一下你的网络情况。
