### ISSUE TITLE
使用cnpm 安装依赖时报错

### ISSUE THREAD

**Issue by shengshiqi** [cnpm/cnpm#388]
cnpm install XXX 正常。cnpm install 报错如下：

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at resolve (/App/data/jenkins_home/node-v10.23.2-linux-x64/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:50:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npminstall version: 5.4.1
npminstall args: /App/data/jenkins_home/node-v10.23.2-linux-x64/bin/node /App/data/jenkins_home/node-v10.23.2-linux-x64/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/App/data/jenkins_home/.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npm.taobao.org/

**Comment by shengshiqi** [comment]
cnpm install 报错。cnpm install XXX 正常
