### ISSUE TITLE
material-vite-ts仓库npm i --registry=https://registry.npmmirror.com正常；cnpm i页面会报错

### ISSUE THREAD

**Issue by Cieeiee** [cnpm/cnpm#408]
仓库：https://github.com/mui/material-ui/tree/master/examples/material-vite-ts

步骤：
1. `cnpm i`
2. `npm run dev`

现象：
在edge，chrome，Firefox中均出现以下错误
```
Uncaught TypeError: (0 , import_react3.withEmotionCache) is not a function
    at emotion-styled-base.browser.esm.js:101:18
    at index.js:20:14
    at createBox (createBox.js:18:4)
    at Box.js:3:13
```
如果用`npm i --registry=https://registry.npmmirror.com`安装依赖则无此问题

环境：
```
  System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 9.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.41)
  npmPackages:
    @emotion/react: latest => 11.10.6
    @emotion/styled: latest => 11.10.6
    @mui/base:  5.0.0-alpha.121
    @mui/core-downloads-tracker:  5.11.13
    @mui/icons-material: latest => 5.11.11
    @mui/material: latest => 5.11.13
    @mui/private-theming:  5.11.13
    @mui/styled-engine:  5.11.11
    @mui/system:  5.11.13
    @mui/types:  7.2.3
    @mui/utils:  5.11.13
    @types/react: latest => 18.0.28
    react: latest => 18.2.0
    react-dom: latest => 18.2.0
    typescript: latest => 5.0.2
```

**Comment by fengmk2** [comment]
感谢反馈，已经复现，会尽快修复。

**Comment by fengmk2** [comment]
@Cieeiee 重新安装一下 cnpm 即可解决问题。
