### ISSUE TITLE
为什么我安装的npm是3.3.5，可是cnpm还是使用2.14.6？

### ISSUE THREAD

**Issue by XGHeaven** [cnpm/cnpm#70]
就是我发现cnpm总是使用node_modules使用的npm，而不是我系统中安装的npm，希望可以修复一下这个问题。关键有时候我用2.14.6的npm安装不上一些包，但是用最新的3.3.5的就可以安装上包。
我现在只能暂时使用alias的方式，好悲剧~

**Comment by fengmk2** [comment]
请问这个安装不来的模块名称叫啥呢？

**Comment by XGHeaven** [comment]
ttystudio

**Comment by fengmk2** [comment]
```
> pty.js@0.3.0 install /private/tmp/node_modules/ttystudio/node_modules/pty.js
> node-gyp rebuild

gyp http GET https://npm.taobao.org/mirrors/node/v4.1.1/iojs-v4.1.1.tar.gz
gyp http 404 https://npm.taobao.org/mirrors/node/v4.1.1/iojs-v4.1.1.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/mk2/npm-global/lib/node_modules/cnpm/node_modules/pangyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
```

发现问题了。

**Comment by XGHeaven** [comment]
能说明一下这个是什么原因么？我是新手不太懂😐

**Comment by fengmk2** [comment]
@XGHeaven 不对，我使用新版的 cnpm 是 ok 的。

```bash
~/git/cnpm/bin/cnpm i ttystudio --loglevel=http
npm http request GET https://registry.npm.taobao.org/ttystudio
npm http 304 https://registry.npm.taobao.org/ttystudio
npm http request GET https://registry.npm.taobao.org/term.js
npm http request GET https://registry.npm.taobao.org/pty.js
npm http request GET https://registry.npm.taobao.org/blessed
npm http 304 https://registry.npm.taobao.org/term.js
npm http 304 https://registry.npm.taobao.org/pty.js
npm http 304 https://registry.npm.taobao.org/blessed
npm http request GET https://registry.npm.taobao.org/extend
npm http request GET https://registry.npm.taobao.org/nan
npm http 304 https://registry.npm.taobao.org/nan
npm http 304 https://registry.npm.taobao.org/extend
|
> pty.js@0.3.0 install /private/tmp/node_modules/ttystudio/node_modules/pty.js
> node-gyp rebuild

gyp http GET https://npm.taobao.org/mirrors/node/v4.1.1/node-v4.1.1-headers.tar.gz
gyp http 200 https://npm.taobao.org/mirrors/node/v4.1.1/node-v4.1.1-headers.tar.gz
gyp http GET https://npm.taobao.org/mirrors/node/v4.1.1/SHASUMS256.txt
gyp http 200 https://npm.taobao.org/mirrors/node/v4.1.1/SHASUMS256.txt
  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node
ttystudio@0.0.16 node_modules/ttystudio
├── term.js@0.0.7
├── blessed@0.1.81
└── pty.js@0.3.0 (extend@1.2.1, nan@2.0.5)
mk2@/tmp node@v4.1.1 
👿  ~/git/cnpm/bin/cnpm -v
3.2.3

```

**Comment by fengmk2** [comment]
发了一个 beta 版本，如果你需要使用 npm3，请通过以下方式安装

```bash
$ npm i -g cnpm@beta --registry=https://registry.npm.taobao.org
```

**Comment by fengmk2** [comment]
```bash
cnpm dist-tag ls
beta: 4.0.0
latest: 3.2.3
```

**Comment by XGHeaven** [comment]
哦，thanks
