### ISSUE TITLE
用cnpm装karma＋jasmine，运行测试报错

### ISSUE THREAD

**Issue by renaesop** [cnpm/cnpm#95]
24 03 2016 10:43:52.314:WARN [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
24 03 2016 10:43:52.322:WARN [reporter]: Can not load "spec", it is not registered!
  Perhaps you are missing some plugin?
24 03 2016 10:43:52.323:WARN [reporter]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?
/Users/fed/Desktop/programming/lpm副本/node_modules/.npminstall/di/0.0.1/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)
    at error (/Users/fed/Desktop/programming/lpm副本/node_modules/.npminstall/di/0.0.1/di/lib/injector.js:22:12)
    at Object.parent.get (/Users/fed/Desktop/programming/lpm副本/node_modules/.npminstall/di/0.0.1/di/lib/injector.js:9:13)
    at get (/Users/fed/Desktop/programming/lpm副本/node_modules/.npminstall/di/0.0.1/di/lib/injector.js:54:19)
    at /Users/fed/Desktop/programming/lpm副本/node_modules/.npminstall/karma/0.13.22/karma/lib/server.js:138:20
    at Array.forEach (native)
    at Server._start (/Users/fed/Desktop/programming/lpm副本/node_modules/.npminstall/karma/0.13.22/karma/lib/server.js:137:21)
    at invoke (/Users/fed/Desktop/programming/lpm副本/node_modules/.npminstall/di/0.0.1/di/lib/injector.js:75:15)
    at Server.start (/Users/fed/Desktop/programming/lpm副本/node_modules/.npminstall/karma/0.13.22/karma/lib/server.js:102:18)
    at Object.exports.run (/Users/fed/Desktop/programming/lpm副本/node_modules/.npminstall/karma/0.13.22/karma/lib/cli.js:243:26)
    at requireCliAndRun (/usr/local/lib/node_modules/karma-cli/bin/karma:44:16)
    at /usr/local/lib/node_modules/karma-cli/bin/karma:54:12
    at /usr/local/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:44:21
    at ondir (/usr/local/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:187:31)
    at /usr/local/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:153:39
    at onex (/usr/local/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:93:22)
    at /usr/local/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:24:18

**Comment by dead-horse** [comment]
是不是有 peerDependencies ?

**Comment by renaesop** [comment]
"devDependencies": {
    "babel-core": "^6.6.5",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.6.0",
    "babelify": "^7.2.0",
    "codecov": "^1.0.1",
    "eslint": "^2.4.0",
    "eslint-config-airbnb": "^6.1.0",
    "eslint-plugin-react": "^4.2.1",
    "isparta-loader": "^2.0.0",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-chrome-launcher": "^0.2.2",
    "karma-coverage": "^0.5.5",
    "karma-firefox-launcher": "^0.1.7",
    "karma-ie-launcher": "^0.2.0",
    "karma-jasmine": "^0.3.7",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-safari-launcher": "^0.1.1",
    "karma-spec-reporter": "0.0.24",
    "karma-webpack": "^1.7.0",
    "phantomjs-polyfill": "0.0.2",
    "phantomjs-prebuilt": "^2.1.5",
    "webpack": "^1.12.14",
    "karma-junit-reporter": "^0.4.1"
  }
这些就是全部依赖了
应该没有peer依赖吧

**Comment by renaesop** [comment]
安装时的警告：
excute post install scripts...
[execSync@1.0.2] scripts.install: "node install.js" at /Users/fed/Desktop/programming/lpm/node_modules/.npminstall/execSync/1.0.2/execSync
[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
[execSync@1.0.2] scripts.install success, use 6s
[fsevents@1.0.9] scripts.install: "node-pre-gyp install --fallback-to-build" at /Users/fed/Desktop/programming/lpm/node_modules/.npminstall/fsevents/1.0.9/fsevents

**Comment by fengmk2** [comment]
能否提供一下能复现的代码。

**Comment by renaesop** [comment]
@fengmk2 [贴了个repo地址](https://github.com/renaesop/test-cnpm.git)
依赖里面有几个模块有peerdependencies， 我猜是jasmine－xxx搞的鬼

**Comment by fengmk2** [comment]
@renaesop 请重新安装 cnpm 接口。

![image](https://cloud.githubusercontent.com/assets/156269/17354052/b11bab9c-5977-11e6-99ef-54bbfc4f49b5.png)

**Comment by renaesop** [comment]
@fengmk2 请问是什么原因导致的呢……

**Comment by fengmk2** [comment]
npminstall 已经按 npm3 的目录结构重新实现。
