### ISSUE TITLE
感觉遇到需要编译的插件就会报错？

### ISSUE THREAD

**Issue by Loyalsoldier** [cnpm/cnpm#98]
我用 cnpm v4.2 安装插件。错误提示如下：

```
node-pre-gyp http Pre-built binary not available for your system, looked for https://npm.t
aobao.org/mirrors/fsevents/v1.0.9/fse-v1.0.9-node-v46-win32-ia32.tar.gz (falling back to s
ource compile with node-gyp)
Traceback (most recent call last):
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node
-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node
-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node
-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node
-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node
-gyp\gyp\pylib\gyp\generator\msvs.py", line 2003, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node
-gyp\gyp\pylib\gyp\generator\msvs.py", line 1762, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node
-gyp\gyp\pylib\gyp\generator\msvs.py", line 1715, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\dev\software\nodejs\node_modules\cnpm\node
_modules\npminstall\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:1
2)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "D:\\dev\\software\\nodejs\\node.exe" "D:\\dev\\software\\nodejs\\node_mo
dules\\cnpm\\node_modules\\npminstall\\node_modules\\node-gyp\\bin\\node-gyp.js" "configur
e" "--fallback-to-build" "--module=D:\\dev\\phpStudy\\Baqianwei-mobile\\node_modules\\.npm
install\\fsevents\\1.0.9\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32\\fse.node"
"--module_name=fse" "--module_path=D:\\dev\\phpStudy\\Baqianwei-mobile\\node_modules\\.npm
install\\fsevents\\1.0.9\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32"
gyp ERR! cwd D:\dev\phpStudy\Baqianwei-mobile\node_modules\.npminstall\fsevents\1.0.9\fsev
ents
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-bui
ld --module=D:\dev\phpStudy\Baqianwei-mobile\node_modules\.npminstall\fsevents\1.0.9\fseve
nts\lib\binding\Release\node-v46-win32-ia32\fse.node --module_name=fse --module_path=D:\de
v\phpStudy\Baqianwei-mobile\node_modules\.npminstall\fsevents\1.0.9\fsevents\lib\binding\R
elease\node-v46-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\dev\phpStudy\Baqianwei-mobile\
node_modules\.npminstall\fsevents\1.0.9\fsevents\node_modules\node-pre-gyp\lib\util\compil
e.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process
.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "D:\\dev\\software\\nodejs\\node.exe" "D:\\dev\\phpStudy\\Baqian
wei-mobile\\node_modules\\.npminstall\\fsevents\\1.0.9\\fsevents\\node_modules\\node-pre-g
yp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\dev\phpStudy\Baqianwei-mobile\node_modules\.npminstall\fsevents\1
.0.9\fsevents
node-pre-gyp ERR! node -v v4.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.24
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\dev\phpStudy\Baq
ianwei-mobile\node_modules\.npminstall\fsevents\1.0.9\fsevents\lib\binding\Release\node-v4
6-win32-ia32\fse.node --module_name=fse --module_path=D:\dev\phpStudy\Baqianwei-mobile\nod
e_modules\.npminstall\fsevents\1.0.9\fsevents\lib\binding\Release\node-v46-win32-ia32' (1)

[Error: Run "C:\windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
" error, exit code 1
    at ChildProcess.<anonymous> (D:\dev\software\nodejs\node_modules\cnpm\node_modules\npm
install\node_modules\runscript\index.js:67:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)@%s] optional
error: %s
All packages installed (747 packages installed from npm registry, use 45s, speed 493.96kB/
s, json 1009(5.61MB), tarball 16.02MB)
```

**Comment by Loyalsoldier** [comment]
BTW，我已翻墙。基本不是网络问题

**Comment by fengmk2** [comment]
你需要自己配置好c++编译环境，windows上请安装编译环境请参考 https://github.com/nodejs/node-gyp/blob/master/README.md

**Comment by Loyalsoldier** [comment]
@fengmk2 

我的 C++ 编译环境是弄好了的，用 npm 安装一切正常。但是 cnpm v4.2 会莫名报错

**Comment by Loyalsoldier** [comment]
刚刚又遇到一个错误，貌似是需要从 Github 直接拉取 Git 仓库的时候，提示说本地项目不是 Git 目录（我本地已经配置好 Git 了）。

我这是用 [tmt-Workflow](https://github.com/weixin/tmt-workflow) 初始化项目，tmt-Workflow 用到尚未发布到 npm 的 gulp v4，所以需要直接从 Git 仓库拉取，然后 cnpm 报错。错误提示：

```
fatal: Not a git repository (or any of the parent directories): .git
Error: [gulp@git://github.com/gulpjs/gulp#4.0]: Run "C:\windows\system32\cmd.exe /d /s /c
git log -1 --format="%H"" error, exit code 128
Error: [gulp@git://github.com/gulpjs/gulp#4.0]: Run "C:\windows\system32\cmd.exe /d /s /c
git log -1 --format="%H"" error, exit code 128
    at module.exports (D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\li
b\download\git.js:51:11)
    at throw (native)
    at onRejected (D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_m
odules\co\index.js:81:24)
```

**Comment by Loyalsoldier** [comment]
找了一下，发现貌似 cnpm v4.2 用了 `npminstall` 这个项目重写 npm install 的过程。而 `npminstall` 又从 `pnpm` 中得到启发而开发出来的。所以我去看了 `pnpm` 的文档，发现 Todo list 里有一项还没完成——从 git 仓库中拉取 package：

![_20160330104656](https://cloud.githubusercontent.com/assets/10487845/14130384/19cb71c0-f665-11e5-89bb-edea015fe995.png)

不知道是不是 `npminstall` 跟 `pnpm` 的开发路径相像，所以导致上面的错误了？

所以现在也只好用回 cnpm v3.x 啦……

**Comment by fengmk2** [comment]
这个git 的问题应该是 bug，我看看。

![image](https://cloud.githubusercontent.com/assets/156269/14131299/7445bb22-f66c-11e5-8c19-359e3c71bea9.png)

**Comment by fengmk2** [comment]
@ibigbug

**Comment by ibigbug** [comment]
git 仓库处理逻辑有 bug，我改一下。

**Comment by fengmk2** [comment]
@Loyalsoldier 重新安装一下 cnpm 即可。已经在 https://github.com/cnpm/npminstall/pull/65 修复。

**Comment by Loyalsoldier** [comment]
安装到一半，编译的插件还是会报错……然后 cnpm 就直接提示所有插件安装成功……Orz

**Comment by fengmk2** [comment]
@Loyalsoldier 能提供 package.json 吗？

**Comment by Loyalsoldier** [comment]
@fengmk2 

如下：

```
{
  "name": "project-test",
  "version": "0.0.1",
  "author": {
    "name": ""
  },
  "dependencies": {
    "autoprefixer": "^6.3.3",
    "browser-sync": "^2.11.1",
    "del": "^2.2.0",
    "gulp": "git://github.com/gulpjs/gulp#4.0",
    "gulp-cssnano": "^2.1.1",
    "gulp-ejs": "^2.1.1",
    "gulp-ftp": "^1.1.0",
    "gulp-if": "^2.0.0",
    "gulp-imagemin": "^2.4.0",
    "gulp-lazyimagecss": "^2.0.0",
    "gulp-less": "^3.0.5",
    "gulp-postcss": "^6.0.1",
    "gulp-posthtml": "^1.5.2",
    "gulp-rename": "^1.2.2",
    "gulp-replace": "^0.5.4",
    "gulp-rev-all": "^0.8.22",
    "gulp-rev-delete-original": "^0.1.0",
    "gulp-tmtsprite": "^0.0.20",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.5.3",
    "gulp-usemin2": "^0.2.4",
    "gulp-util": "^3.0.7",
    "gulp-webp": "^2.3.0",
    "gulp-zip": "^3.2.0",
    "imagemin-pngquant": "^4.2.2",
    "lodash": "^4.5.1",
    "postcss-pxtorem": "^3.3.1",
    "posthtml-px2rem": "^0.0.3",
    "rc": "^1.1.6",
    "rd": "^0.0.2",
    "tmt-ejs-helper": "^0.0.1"
  }
}
```

**Comment by Loyalsoldier** [comment]
@fengmk2 

看样子应该是 fsevents 无法编译，下面的错误提示里有这样一个提示：

**AttributeError: 'MSVSProject' object has no attribute 'iteritems'**，貌似是说 Visual Studio Community 2015 却了个什么鬼属性？

错误提示：

```
[fsevents@1.0.9] scripts.install: "node-pre-gyp install --fallback-to-build" at D:\test\node_modules\.npminstall\fsevents\1.0.9\fsevents
node-pre-gyp http GET https://npm.taobao.org/mirrors/fsevents/v1.0.9/fse-v1.0.9-node-v46-win32-x64.tar.gz
node-pre-gyp http 404 https://npm.taobao.org/mirrors/fsevents/v1.0.9/fse-v1.0.9-node-v46-win32-x64.tar.gz
node-pre-gyp http Pre-built binary not available for your system, looked for https://npm.taobao.org/mirrors/fsevents/v1.0.9/fse-v1.0.9-node-v46-win32-x64.tar.gz (falling back to source compile with node-gyp)
Traceback (most recent call last):
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2003, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1762, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1715, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "D:\\dev\\software\\nodejs\\node.exe" "D:\\dev\\software\\nodejs\\node_modules\\cnpm\\node_modules\\npminstall\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\test\\node_modules\\.npminstall\\fsevents\\1.0.9\\fsevents\\lib\\binding\\Release\\node-v46-win32-x64\\fse.node" "--module_name=fse" "--module_path=D:\\test\\node_modules\\.npminstall\\fsevents\\1.0.9\\fsevents\\lib\\binding\\Release\\node-v46-win32-x64"
gyp ERR! cwd D:\test\node_modules\.npminstall\fsevents\1.0.9\fsevents
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\test\node_modules\.npminstall\fsevents\1.0.9\fsevents\lib\binding\Release\node-v46-win32-x64\fse.node --module_name=fse --module_path=D:\test\node_modules\.npminstall\fsevents\1.0.9\fsevents\lib\binding\Release\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\test\node_modules\.npminstall\fsevents\1.0.9\fsevents\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "D:\\dev\\software\\nodejs\\node.exe" "D:\\test\\node_modules\\.npminstall\\fsevents\\1.0.9\\fsevents\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\test\node_modules\.npminstall\fsevents\1.0.9\fsevents
node-pre-gyp ERR! node -v v4.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.24
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=D:\test\node_modules\.npminstall\fsevents\1.0.9\fsevents\lib\binding\Release\node-v46-win32-x64\fse.node --module_name=fse --module_path=D:\test\node_modules\.npminstall\fsevents\1.0.9\fsevents\lib\binding\Release\node-v46-win32-x64' (1)
[Error: Run "C:\windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build" error, exit code 1
    at ChildProcess.<anonymous> (D:\dev\software\nodejs\node_modules\cnpm\node_modules\npminstall\node_modules\runscript\index.js:67:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)@%s] optional error: %s
All packages installed (786 packages installed from npm registry, 1 packages installed from git, use 1m, speed 75.09kB/s, json 968(5.17MB), tarball 12.33kB)
```

**Comment by alsotang** [comment]
http://npm.taobao.org/package/fsevents 这是一个 osx 专用的包。。。。。竟然在win上开始了编译

2016-03-31 19:05 GMT+08:00 Weixian Liu <notifications@github.com>:

**Comment by fengmk2** [comment]
呃，这个编译肯定错误啊，模块压根地不支持windows。而且它只是编译失败又是optional dep，不影响你整个包安装的，你看最后一行日志，是安装成功的。

**Comment by Loyalsoldier** [comment]
我还以为最后“所有 packages 安装成功”的提示是骗人的呢……233
